/**
 * Seznam změn aplikace.
 *
 * Odděleno od version.ts schválně: číslo verze potřebuje patička na každé
 * obrazovce, kdežto tenhle seznam (přes 50 kB) čte jen admin v Nastavení.
 * V jednom souboru by se stahoval při každém spuštění aplikace.
 */
// Stručný přehled změn v aktuální verzi (zobrazuje se v admin sekci Nastavení)

export const APP_CHANGELOG: string[] = [
  '🔒 Do aplikace se nahrávaly i soukromé zprávy. Vlastní zprávy (from_me) obcházely whitelist na všech čtyřech místech, kde brána žije — na mostu, na webhooku, v automatickém čtení i v triggeru databáze — takže do provozní databáze spadlo všechno, co majitel na WhatsAppu napsal, objednávky i osobní konverzace. A v aplikaci to pak viděl každý, kdo do ní má přístup. Ta výjimka měla řešit objednávku napsanou z vlastního telefonu do objednávkové skupiny; na to ale žádná není potřeba, protože skupina je ve whitelistu zapsaná jménem i chat_id a vlastní zpráva z ní projde běžnou branou stejně jako zákaznická. Výjimka tedy nepouštěla dál nic, co mělo projít — jen všechno ostatní. Příznak from_me zůstává, aplikace podle něj vlastní zprávu dál odliší od zákaznické: rozhoduje o popisku, ne o vstupu. Zavřená je i druhá polovina díry — „prázdný whitelist = povoleno vše" už neplatí na soukromé zprávy; u skupin je to zpětná kompatibilita a zůstává, ale nevyplněný whitelist je nedopatření, ne pokyn ke čtení osobní pošty. Rozhodování je nově čistá funkce se 17 testy (bylo 10) — tatáž díra se totiž otevřela už dvakrát, protože bylo rozepsané v podmínkách, kde ho nešlo otestovat. 🕐 Objednávky ke kontrole se načítají OD NEJSTARŠÍCH. Je to fronta práce, ne zpravodajství: objednávka z pondělí se dřív propadala pod každou novou zprávou a zbyla na konec, přitom u objednávky s termínem závozu je zdržení tím dražší, čím dýl leží. Po potvrzení jedné se skáče na tu, co čeká nejdéle. Řazení v seznamu se dá přepnout zpátky na nejnovější. 🖐️ Dlaždice na Domů nešlo chytit — místo přesunu se označil text. Sešly se tři věci: zákaz scrollování se dlaždici nasazoval až po 400 ms podržení, přitom prohlížeč se rozhoduje hned při prvním dotyku, takže si gesto vzal na scroll a tažení umřelo; myš navíc rozjížděla výběr textu, takže se táhl označený popisek a dlaždice zůstala stát. Text teď nejde chytit nikde kromě míst, kde se s ním pracuje — polí a poznámek. A přesun je plynulejší: pohyb prstu se přepočítává jednou za snímek místo při každé z desítek událostí za sekundu, kvůli kterým dlaždice za prstem kulhala.',
  '🗓️ Týdenní inventura — nová záložka v Inventuře. Měsíční uzávěrka je poctivá, ale pozdní: když se v půlce srpna nezapíše stáčení, přijde se na to až koncem měsíce a dohledávání je pak archeologie. Tady je smyčka sedmidenní — rozdíl se hledá v týdnu, který má člověk ještě v hlavě. Počítá se jen to, co má cenu počítat: položky se stavem, s pohybem za ten týden nebo už rozepsané, ne všech tři sta kombinací pivo × obal z katalogu. Rozdělaná práce se drží, takže sklep se dá spočítat dnes a sklad zítra. Očekávaný stav bere táž skladová kniha jako Sklad a měsíční inventura, žádná nová matematika. 🛠️ Rozdíl se ale NEUKLÁDÁ jako nový stav — řádek v inventuře je reset, který by rozdíl tiše spolkl: číslo by sedělo, ale stáčení KEG, stáčení lahví ani sklad by o něm nevěděly. Propíše se proto tam, kde vznikl: přebytek jako chybějící zápis stáčení (u sudů i s odečtem z tanku, na kterém to pivo leží), manko jako záporný řádek. Co s výrobou nesouvisí (rozbité, ztracené), jde na „Dorovnat" bokem — schválně jako druhá volba, protože schovat rozdíl tam je snadné a nic to nevysvětlí. U běžícího týdne se počítá po dnešek, aby zápis výroby nespadl do budoucnosti.',
  '📱 Ovládání na telefonu, druhá dávka. 🚨 Výstražné dlaždice na Domů („Vozidla — STK/známka", „WhatsApp nechodí") měly ikonu VEDLE textu, jenže na jednotkové dlaždici široké 84 px si ikona a odsazení vzaly 61 px a na popisek zbylo 23 — text se zlomil doprostřed slova na „Voz id…" a nešlo poznat, co hlásí. Ikona jde teď nad text a popisek má celou šířku i tři řádky. 🏷️ Spodní lišta: popisky se ořezávaly na pevných 64 px, přestože slot je široký 89 („Lahve (Stá…"). Popisek teď respektuje skutečnou šířku slotu, ať jsou v liště dva zástupci nebo šest. 📊 Statistika: záložky měly dohromady 876 px, ale pruh jich má 347 — vidět byly necelé tři a na zbytek se rolovalo naslepo. Na telefonu se pruh zalamuje, takže je všech osm vidět naráz; přilepení nahoře zůstává jen na širším displeji, kde se vejdou na řádek. Dvě záložky se navíc na telefonu jmenovaly stejně („Výstav") a nešlo poznat, která otevře co — druhá je teď „HL & KEG/PET". 🖨️ Odstraněny zdvojené ikony v tlačítkách (Rychlé sčítadlo skladu, Spustit fotoaparát, Vybrat fotku, Měsíční uzávěrka) — zbytek po převodu emoji na kreslené ikony, kde stará i nová zůstaly vedle sebe.',
  '📱 Ovládání na telefonu — oprava toho, proč byla zaškrtávátka „mimo" a kolečka „roztažená". Mobilní pravidlo dávalo výšku 44 px KAŽDÉMU poli, tedy i zaškrtávacím políčkům a kolečkům: ta jsou 13 px široká, takže z nich byla svislá nudle 13 × 44 px se symbolem ustřeleným mimo popisek. Stejné pravidlo dělalo z barevného vzorku (28 px kolečko v úpravě plochy) ovál 28 × 44 a posuvníkům bralo dráhu. Políčka i kolečka jsou teď všude stejná, čtvercová a na dotyk 24 px; nesmrští se ani v řádku s dlouhým textem, ani se nenatáhnou podle sousedního pole. 🔍 Pole s ikonou uvnitř (vyhledávání v Odběratelích, Uživatelích, Prodejně, Auditu — 16 míst) přišla na telefonu o odsazení pro tu ikonu, takže se lupa kreslila přes první písmeno; odsazení si teď pole udrží. 🎯 Šipkové přepínače „‹ ›" (měsíc, týden) byly 21–28 px široké při výšce 44 px — svislá nit, do které se prstem trefit nedalo; mají teď plnou šířku palce, stejně jako každé jiné ikonové tlačítko bez zadané šířky. 📐 Zalamované řady tlačítek (Objednávky, Sklad, Závoz, Inventura, Uživatelé…) se na telefonu lámaly do schodů, protože se každý zalomený řádek zarovnával zvlášť doprava — teď tlačítka dorostou do plné šířky řádku a levé hrany sedí pod sebou. 🎨 Domů: dlaždice Export do Excelu doplněna na plochu a barvy sjednoceny podle kategorie (oranžová Výroba, modrá Pivovar, fialová Nástroje, zelená Číselníky, šedá Nastavení) — Pivovar se přebarvil z tyrkysové na modrou, od zelených Číselníků ho dělilo příliš málo.',
  '🛢️ Stáčení KEG bez tanku se ukládalo TIŠE — a spolu s číslem tanku propadl i odečet objemu ze sklepa. Tank se totiž řádku přiřadí, jen když je zrovna na nějakém tanku s tím pivem „Zahájené stáčení"; když není, řádek se uložil beze slova. Takhle zmizel tank u 82 ze 198 zápisů: červenec a začátek srpna se zapisovaly zpětně 2.–9. 8., tedy dřív, než sklep v appce vůbec existoval (všechny tanky vznikly 9. 8. v 16:13), a u dalších dnů prostě nebylo stáčení zahájené. Tytéž zápisy pak z tanku neubraly ani litr — odtud i schodek 2 000 l na Spilce 1 a 5 400 l na Tanku 6, který Sklep hlásí. Nově se uložení bez tanku musí potvrdit a dialog vypíše, kterých řádků se to týká; v úpravě staršího zápisu jde navíc vybrat i tank, na kterém už stáčení skončilo, takže se číslo dá doplnit dodatečně. 📅 Napočítaná inventura patří k POSLEDNÍMU dni měsíce, ne k prvnímu. Ukládala se k prvnímu a skladová kniha ji bere jako výchozí stav, ke kterému přičítá všechny další pohyby — takže k napočítanému číslu přičetla ještě celý inventovaný měsíc. Srpen, 12° Světlá 50 l: napočítány 4 sudy, Sklad z nich udělal 4 + 95 − 77 − 25 = −3, kdežto Inventura ze zapsaného počátku 11 vyšla taky na 4. Dvě strany téhož měsíce si přímo odporovaly a 29 z 56 kombinací pivo × obal svítilo v mínusu. 📊 Tabulka Skladu navíc počítá měsíční rozpad, ne „stav od poslední inventury" — sloupce se čtou jako „počáteční + stočeno − výdeje = stav", což je přesně to, co počítá Inventura, takže obě obrazovky teď ukazují stejná čísla. ⏰ A WhatsApp most se přestal uspávat: běží na bezplatném Renderu, který ho po 15 minutách ticha uspí, a spící most není připojený k WhatsAppu, takže zprávy nikam nechodí. 1. 9. takhle propadlo 33 hodin zpráv. Databáze ho teď každých 5 minut probudí.',
  '🧪 Čtení objednávek dostalo 66 testů na to, jak lidi objednávky doopravdy píšou — obtažených podle skutečných zpráv ze skupiny, ne vymyšlených. Stupeň před objemem i za ním („12sv 3x50l" i „10x50l 12sv"), slovem („desítka", „dvanáctky", „vosma", „jedenáctka"), se znakem ° i bez, vlastní jména piv (Jantar, Summer), „vše 11%" na konci, víc obalů na jednom řádku, PET, bedny, víc objednávek na jednom řádku. Vyšlo z toho sedm dalších míst, kde se pivo nebo obal nepřiřadily: větev, která zakládá objednávky z WhatsAppu, neznala hovorové tvary („8 sudů 30l na pátek, desítka" pro ni nebylo pivo vůbec) a objem v obalu hledala způsobem, který na zápis „13x50l" nesedl — stejná chyba, jaká byla ráno ve stáčení KEG z fotky. 🔍 Hlavní věc ale je, že tahle serverová větev šla vůbec poprvé otestovat: matcher seděl uvnitř edge funkce, odkud ho žádný test neuměl spustit, a přesně v něm vznikla chyba „všude Osma". Je teď v samostatném souboru vedle ní. Klientská větev (čtení z fotky, ruční import) dostala tytéž varianty, aby objednávka dopadla stejně bez ohledu na to, kudy do appky přišla.',
  '🍺 Objednávka napsaná na jeden řádek přiřazovala všem položkám stejné pivo. U zprávy „Restaurace 1x50 12, 1x50 10 a 1x50 tm, terasa 2x50 12 2x50 osma" se do všech pěti položek zapsala Osma — přestože stupně (12°, 10°, 12°, 12°, 8°) se přečetly správně. Důvod: všech pět položek dostane od AI stejný raw text, celý ten řádek, a pivo se hledá tak, že v textu stačí najít název z katalogu. Slovo „osma" na konci řádku tak vyhrálo úplně u všech. Nově nález z řádku neplatí, když odporuje stupni TÉ položky — a když si stupeň s ničím nesedne, položka zůstane bez piva a doplní se ručně, místo aby dostala cizí. 🎯 Zároveň se přestalo losovat u holého stupně: „12" sedí na 12° Světlou i 12° Tmavou a dosud rozhodovalo pořadí, v jakém piva přišla z databáze — výsledek se měnil zprávu od zprávy. Teď platí zvyk pivovaru: tmavé se v objednávce vždycky označí, takže neoznačený stupeň znamená světlé. Ověřeno na té skutečné zprávě z 28. 8.: čte se z ní 12° Světlá, 10° Desítka, 12° Tmavá, 12° Světlá a Osma. 📱 A popisky dlaždic na Domů se na telefonu už nesekají — delší názvy jako „Vozidla — STK/známka" nebo „Odběratelé, Piva, Obaly, Ceník" přetékaly ven z dlaždice.',
  '📱 Šipky a tečky na přepínání stránek na Domů byly na telefonu roztažené do svislých pilulek — kolečka 30 px do výšky 44 px a osmipixelové tečky do osmi na šířku a 44 na výšku. Mohlo za to pravidlo, které na dotykových zařízeních dává každému tlačítku bez zadané výšky aspoň 44 px, aby se dalo trefit prstem. Jenže „zadanou výšku" umí poznat jen u tlačítek stylovaných Tailwindem, podle názvů tříd — a tyhle ovládací prvky si velikost určují ve vlastním CSS. Přibyla proto značka „velikost je tady schválně", kterou pravidlo respektuje; na telefonu teď vypadají stejně jako na počítači. 📩 A řádek „X zpráv z WhatsAppu ke kontrole" v panelu Dnešek otevře rovnou okno s objednávkami ke kontrole, ne jen seznam objednávek — stejně jako to od minule dělá upozornění na novou objednávku.',
  '📩 Upozornění „NOVÁ WHATSAPP OBJEDNÁVKA K OVĚŘENÍ" teď opravdu vede ke kontrole. Jeho tlačítko dosud jen přepnulo na Objednávky a člověk skončil u obyčejného seznamu — okno s objednávkami ke kontrole si musel otevřít sám. Nově otevře rovnou ho (a jmenuje se „Zkontrolovat objednávku"). Stejně tak ikona WhatsApp v hlavičce: když jste už na Objednávkách, dosud po kliknutí nevyskočilo nic, protože se okno otevíralo jen při prvním otevření obrazovky. 🏠 Z horní řady na Domů zmizela dlaždice „Objednávky k parsování" — dělala potřetí totéž, co to upozornění a ikona WhatsApp v hlavičce. Upozorňovací dlaždice (Vozidla — STK/známka, Nová aktualizace, Měsíční úklid) zůstávají.',
  '🧽 Měsíční úklid se ptá jednou za měsíc, ne každý den. Odškrtané checklisty se ukládají po dnech, takže „hotovo" platilo jen pro ten jeden den — druhý den posledního týdne se okno s měsíční údržbou otevřelo znovu, přestože byl úklid udělaný a zapsaný v sanitárním deníku. Dokončení se nově drží na měsíc a zvlášť pro lahve a pro KEGy: jakmile je linka hotová, ozve se až v posledním týdnu dalšího měsíce. Odškrtnutí se navíc pamatuje přes celý poslední týden — úklid se běžně dělá na dvakrát (dnes stáčečky, zítra podlahy) a dosud počítadlo každý den začínalo od nuly. 📷 A fotky: v KEG stáčení tlačítko „Spustit fotoaparát" NEDĚLALO NIC — vyfocený snímek se ukládal do fronty, kterou nikdo nečetl. Objem sudu se hledal způsobem, který na běžné zápisy „4x50" nebo „2x30l" vůbec nesedl, takže obal zůstával prázdný. A u lahví i KEGů se řádky bez rozpoznaného piva při potvrzení POTICHU zahodily a okno se zavřelo, takže to vypadalo, že tlačítko nefunguje — teď řekne, u kterého řádku pivo chybí. Zaškrtnutí „Oříznout / Otočit fotku před čtením" se také nikde nečetlo a fotka šla do čtení neupravená.',
  '🎨 Sjednocený vzhled celé aplikace. Běžely tu vedle sebe DVĚ sady barev, které znamenaly totéž a vypadaly jinak — podle obrazovky svítilo varování jednou zlatě a podruhé oranžově, chyba jednou růžově a podruhé červeně. Sjednoceno 479 tříd na jednu sadu a pět mrtvých sad škrtnuto z nastavení (jedna neměla ani jedno použití). Vedlejší zisk: tmavý režim tu druhou sadu vůbec neznal, takže v něm 466 míst zůstávalo světlých. 📏 374 míst mělo písmo 8, 9 nebo 10 px — nejvíc v Historii, Inventuře a Skladu, tedy tam, kde se čtou čísla; spodní hranice je nově 11 px. 👆 A hlavně: z 892 tlačítek jich 628 nemělo zadanou výšku a na telefonu vycházela kolem 32 px. Na dotykových zařízeních mají nově všechna aspoň 44 px, na počítači se nemění nic, aby nezřídly tabulky. 🚫 Odstraněno taky 404 emoji, která jen zdvojovala text vedle sebe. Barvu i velikost písma teď hlídá test, takže se rozdíl nemůže vrátit první nově napsanou obrazovkou.',
  'Fasování je jeden formulář se třemi možnostmi. „Fasování personál" se jmenuje prostě Fasování a nahoře v zápisu je otázka „Kam se vydává" se třemi odškrtávacími poli: Prodejna, Personál, Odpis. U Prodejny nic navíc, u Personálu se objeví pole „Pro koho" (jméno), u Odpisu pole „Důvod odpisu". Formulář je jinak stejný, takže se nemusí přebíhat mezi třemi obrazovkami — a podle zaškrtnutí se zápis sám uloží tam, kam patří, takže v měsíčním exportu spadne do správného listu (Fasování prodejna / Odběr personál / Vzorky promo a PR). Přepínač byl dřív schovaný nahoře jako drobná navigace; teď sedí přímo nad polem, které mění, a jeho tlačítka jsou dost velká na prst.',
  'Dostránkováno všech 47 zbývajících dotazů na rostoucí tabulky — Historie, Objednávky, Závoz, Sklep, Akce, Kniha jízd, plánovač stáčení, konto sudů, sklad etiket a další. Supabase vrátí nejvýš 1000 řádků a zbytek TIŠE zahodí; jakmile tabulka hranici přeroste, část dat se prostě přestane počítat a nic nespadne — přišlo by se na to až podle nesedící inventury, měsíce potom. Objednávek je 166 a rostou zhruba o padesát měsíčně, položek 497. Hlavně ale přibyly DVĚ POJISTKY, které tuhle třídu chyby zavírají natrvalo: jeden test projde zdrojáky a najde každý nový dotaz na rostoucí tabulku, který se nestránkuje; druhý hlídá, že se stránkovaný dotaz nezavolá s něčím, co neumí (to TypeScript nepozná a spadlo by to až uživateli na obrazovce). Obě jsem ověřil tím, že jsem chybu schválně vyrobil a nechal ji chytit.',
  'Odstraněná časovaná bomba: devět dotazů „položky těchhle objednávek" se posílalo jedním požadavkem, jenže Supabase vrátí nejvýš 1000 řádků a zbytek TIŠE zahodí — bez chyby, bez varování. Týkalo se to Historie, Závozu, Objednávek, Sklepa, obou kontrol objednávek a panelu Dnešek. Položek objednávek je dnes 497 a rostou zhruba o dvě stě měsíčně; až by tabulka přerostla tisícovku, začaly by objednávky v aplikaci vypadat menší, než jsou, a sklad by z nich počítal špatně — a nic by nespadlo, takže by se na to přišlo až podle nesedící inventury. Past je u těchhle dotazů větší než u obyčejných: položek je násobně víc než objednávek, takže hranici přerostou dřív než tabulka sama. Všechny se teď načítají po stránkách a hlídá to šest testů.',
  'Výdej (fasování / prodejna / odpis) na telefonu. Přehled byl šestisloupcová tabulka a ovládací tlačítka v ní měla 24 × 24 px — křížek „smazat" přitom sousedil s plusem, takže jedno nepřesné klepnutí prstem místo přidání kusu smazalo celý zápis. Na telefonu jsou z toho karty: pivo, obal a datum nahoře, velké množství vpravo a pod tím tlačítka na výšku prstu, kde je křížek schválně odsazený od plusu. Tabulka zůstává na počítači. Zvětšily se taky šipky ‹ › na přepínání dne, týdne a měsíce ve stáčení KEG i lahví — listuje se jimi pořád a měly čtvrtinu potřebné plochy.',
  'Čekající zápisy ze sklepa je konečně poznat. V seznamu offline fronty stálo „orders · insert" — z toho nikdo nepozná, o co jde; nově je tam „Objednávka — nový zápis: Bar U Sadu" nebo „Stáčení KEG — nový zápis: 12° Světlý ležák · 50 l · 3 ks". Důvod, proč zápis uvízl, se navíc drží i po restartu aplikace: dřív byl jen v paměti, takže po zavření appky vypadal rozbitý zápis jako každý jiný čekající a nešel odklidit — jediná možnost bylo vysypat celou frontu i s dobrými zápisy. Zahodit jde teď kterýkoli jednotlivý zápis (s dotazem). A když v telefonu dojde místo, řekne se to česky místo „QuotaExceededError". Celou frontu nově hlídá 17 testů — je to místo, kde tichá chyba znamená ztracený zápis ze sklepa. ♻️ Přibyla taky obnova ze zálohy: zálohy do GitHubu běžely od v1.908, ale vrátit je zpátky šlo jen ručním klikáním v Supabase. Viz zalohy/OBNOVA.md.',
  'Potřeba stočit (KEG i lahve) přepracovaná na telefon. Přepínač dnů se drží nahoře i při rolování, takže je pořád vidět, na který den se díváte. Nahoře místo tří karet přes celou obrazovku jeden proužek „Zbývá X · hotovo Y/Z" — práce začíná hned, ne až po odscrollování čísel. U položky je velké číslo „zbývá" a pod ním tlačítka −, + a „Mám všech N" přes celou šířku; „odběratelé" a „Objednávky" byly jedenáctibodové odkazy, teď jsou to tlačítka na výšku prstu. Přibylo hledání podle piva nebo obalu (bez háčků) a přepínač „Jen co chybí" — denní seznam mívá přes deset položek. U lahví se osmisloupcová tabulka na telefonu vejde jen s vodorovným rolováním, takže „kolik stočit" bylo schované za okrajem: nově jsou z ní karty, kde je to číslo největší. Filtry v tabulce se navíc lepí úplně nahoru, ne pod nadpis.',
  'Úkoly k závozu — co kromě piva naložit nebo přivézt zpátky. Požadavky jako „ještě vyzvednout sudy v ASI" chodily ve zprávě jako věta mezi objednávkou a skončily nanejvýš jako řádeček kurzívy v poznámce, kde se při nakládání auta přehlédly. Nově se z poznámky vytáhnou konkrétní úkoly a jsou vidět na třech místech: barevný štítek u odběratele v Závozu, souhrn „Nezapomeňte k tomuhle dni" nad seznamem objednávek dne (u koho co) a řádek na Domů v panelu Dnešek — u zítřejšího i dnešního závozu. Vyzvednutí prázdných sudů svítí červeně, protože se dělá na místě a při zapomenutí znamená cestu znovu. Rozpoznává se vyzvednutí sudů, vratné lahve a přepravky, výčep a pipy, sklo, podtácky, spoták a faktura. Vyzvednutí sudů se navíc nově pozná i při čtení zprávy z WhatsAppu — dřív se do poznámky nedostalo vůbec.',
  'Mazání se už neptá — nabídne vrácení zpět. U stáčení KEG, stáčení lahví a výdeje (fasování / prodejna / odpis) se před smazáním vyskakoval dotaz, takže každé mazání stálo dvě klepnutí, i když se člověk nespletl. Nově řádek zmizí hned a pár vteřin dole svítí „Vrátit zpět". U KEGů vrácení zase odečte objem, který se mazáním vrátil do tanku. Mazání ve stáčení lahví navíc dřív neohlásilo chybu: řádek zmizel z obrazovky, ale v databázi zůstal. ⚡ A aplikace startuje znovu o dost rychleji — úvodní stažení kleslo z 266 na 70 kB (o 74 %). Stahovala se totiž při každém spuštění knihovna na Excel, celý seznam změn aplikace a parser objednávek, přestože je většina spuštění nepoužije. v1.941',
  'Inventura na telefonu: přibyl režim počítání. Nahoře je vidět postup (kolik z kolika je hotovo) a čtyři filtry — Vše, Chybí spočítat, Jen s pohybem, Nesedí. Bez toho se ve skladu prochází všech 99 kombinací pivo × obal a není poznat, co už máte. Zvětšil jsem taky 23 malých tlačítek na velikost, která se dá na dotyk trefit. 💾 A přibyla bezplatná denní záloha objednávek a stáčení do GitHubu — každý den jeden commit, takže se dá vrátit ke stavu k libovolnému dni. Stačí přidat jeden klíč, viz zalohy/README.md. v1.908',
  'Kontrola po sjednocení výpočtů — a dvě další nesrovnalosti k tomu. Plán stáčení lahví a plánovač si nenačítaly přefuk ani dorovnání inventury, takže i po sjednocení ukazovaly jiná čísla než Sklad; plán lahví navíc nevěděl o sudech spotřebovaných na lahve. Teď dostává všech sedm míst identická data. Druhá věc byla časovaná: Supabase vrací nejvýš 1000 řádků na dotaz a zbytek TIŠE zahodí — odečty závozu jsou na 473, položky objednávek na 496, takže za pár měsíců by sklad začal počítat špatně a nic by nespadlo. Všech 68 dotazů na rostoucí tabulky se teď načítá po stránkách. v1.907',
  'Napočítaná NULA se konečně ukládá — a tím je odhalená příčina toho deficitu. Inventura dosud zahazovala každý řádek s nulou (v aplikaci i v databázi), takže \"díval jsem se a není tam nic\" se změnilo na \"o téhle položce nic nevím\". To jsou ale dvě úplně jiné věci: uložená nula je pevný základ, od kterého se počítá dál, kdežto chybějící řádek nechá sklad sáhnout po starší inventuře a odečítat od ní všechny závozy. Proto měla schválená inventura za červenec jen 19 řádků z 56 a k 26. 8. vycházelo 34 položek do mínusu. Inventura navíc nahoře vypíše položky, které se tenhle měsíc hýbaly, ale nemají vyplněný stav — ať při počítání nic neuteče. v1.906',
  'Všechny skladové výpočty počítají konečně stejně. Sklad si dosud počítalo SEDM různých míst po svém (Sklad, Domů, Inventura, potřeba stočit sudy i lahve, plánovač stáčení) a kopie se rozcházely — přefuk chyběl ve třech ze čtyř, Akce se nepočítaly vůbec, dorovnání inventury jinde. Teď je matematika na jednom místě. Inventura navíc přestala číst sklad z paměti prohlížeče: počáteční stav měsíce i fyzická inventura mohly existovat jen na jednom zařízení a jinde svítila jiná čísla. A očekávaný stav se v Inventuře počítá tak, aby ho neovlivnila inventura, kterou zrovna zapisujete — jinak by rozdíl vždycky vyšel nula a manko by nešlo zjistit. v1.905',
  'Odpovědi na WhatsApp objednávky se konečně čtou. Ve skupině se běžně odpovídá \"Bez summera\", \"nakonec 9x30\", \"plus 3x10 11sv\" — dosud z toho buď vznikla DRUHÁ objednávka pro téhož odběratele, nebo se zpráva zahodila (u \"Radek nakonec summer 9x30\" jste ručně opravoval 15 ks na 9, přestože odpověď na to doslova odpovídala). Nově se odpověď naváže na původní objednávku a v kontrole se ukáže CELÁ objednávka se zvýrazněnými změnami: zeleně přidané, žlutě změněné, škrtnuté odebrané. Schválením se objednávka upraví, nová se nezaloží. Dotaz, který nic nemění (\"Je nějaký Summer navíc?\"), objednávku nechá být. v1.904',
  'Sklad počítá nově — jako účetní kniha. Dosud se každý pohyb zvlášť ořezával na nulu, takže když se vydalo víc, než kolik appka věděla, schodek zmizel a sklad hlásil 0. Skrývalo to skutečný problém: u 34 z 56 položek evidence nesedí (12° Světlá 1l −166 ks, 12° Tmavá 0,33l −160 ks, 11° Světlá 30l −12 ks). Nově se stav počítá od poslední inventury a nic se neořezává; položky, kde to nesedí, jsou nahoře ve Skladu vypsané i s tím, o kolik a od které inventury. Srovná je fyzická inventura. Zároveň je matematika na JEDNOM místě místo v sedmi kopiích, které se rozcházely. v1.902',
  'Odškrtávátko v plánu stáčení už NEZAPISUJE stáčení — je to jen přehled, abyste viděli, co máte hotové. Stáčení se dál zapisuje v \"Začátek stáčení\" a jenom to hýbe skladem a objemem tanku. Odškrtnutí se ukládá zvlášť (vidí ho i kolega na jiném zařízení) a se skutečně zapsaným stáčením se skládá tak, že se nepočítá dvakrát: když si položku odškrtnete a pak ji poctivě zapíšete, zůstane započítaná jednou. v1.901',
  'Stará záložka \"Potřeba stočit KEGy\" je pryč — počítala z měsíčního skladu, který se rozešel s realitou, a ukazovala jiná čísla než denní rozpad. Nahradila ji záložka \"Co stočit na který den\", která teď umí i \"Celý týden\": stejný přehled pivo × obal za celý týden, ale sečtený z těch samých denních dat, takže se s nimi nemůže rozejít. Přenesené je i klikání na \"Zobrazit objednávky\" u chybějící položky. v1.900',
  'Souhrn nad tabulkou \"Potřeba stočit KEGy\" počítal jen řádky, kde něco chybělo — hlásil proto 75 objednaných sudů, i když jich bylo 119. Přepínač \"Jen chybějící\" teď schovává řádky v tabulce, ale karty nahoře už neořezává. v1.899',
  'Oprava chybně přiřazovaných položek z WhatsAppu. Když jste v kontrole objednávky opravili pivo, uložilo se z toho TRVALÉ pravidlo pro všechny budoucí zprávy — i když opravovaný text pivo pojmenovával správně. Takhle se v databázi usadilo mimo jiné \"jantar → 12° Světlá\", \"10° desítka → 11° Světlá\" a 41 pravidel typu \"2x10\" nebo \"7x50\" (počet × objem, o pivu nic), která se pak hledala jako podřetězec a sedla na kdejakou další zprávu. Vyčištěno 58 vadných pravidel ze 177 a doplněny dvě pojistky: zapamatuje se jen text, který pivo skutečně pojmenovává, a nikdy ne přepis jednoho piva z katalogu na jiné. Navíc se u položky srovnal název piva s jeho ID — 25. 8. vznikla položka, kde na obrazovce svítila 11° Světlá, ale do objednávky se založila 10° Desítka. v1.898',
  'V KEGu přibyla záložka "Co stočit na který den" — ovládá se jako Závoz: kliknete na den a vidíte, co a kolik sudů je na něj potřeba, kolik už je hotovo a kolik chybí, včetně toho pro koho. Tlačítkem "Mám" nebo "+1" si sudy odškrtáváte a zápis stáčení se uloží rovnou, takže se nikde nevede druhá evidence. Zároveň to opravuje starou potíž, že se čerstvě stočený sud neodečetl hned z "potřeba stočit": to číslo se počítalo z měsíčního skladu, který se rozešel s realitou (devět druhů sudů bylo v srpnu v mínusu kvůli chybějícímu převodu z července) a nový sud pak nejdřív umazával neexistující dluh. Nový plán počítá jen s daty aktuálního týdne a řídí se odečtem u konkrétní objednávky, takže nachystané sudy nechce stočit podruhé. v1.897',
  'Aplikace startuje výrazně rychleji: dosud se při každém otevření stáhlo všech ~40 obrazovek najednou (2,9 MB), i když jste chtěli jen Domů — skoro třetinu z toho dělala knihovna pro export do Excelu, používaná jednou za měsíc. Teď se stahuje jen to, co skutečně otevřete; úvodní stažení kleslo o 73 %. Na mobilních datech v pivovaru je to rozdíl několika sekund při každém spuštění i po každé aktualizaci. v1.896',
  'Sjednocena práva k obrazovkám: seznam "která obrazovka patří pod které oprávnění" existoval v aplikaci třikrát a kopie se rozešly — Šrotování patřilo jednou pod vlastní modul a jinde pod Zápis výroby, a Odběratelé/Piva/Obaly v jedné kopii chyběli úplně, takže se zobrazovali i lidem bez práv. Teď je seznam na jednom místě a hlídá ho test. v1.892',
  'Záloha dat byla neúplná: stahovala se po tisíci řádcích a zbytek se TIŠE zahodil (bez chyby), takže záloha vypadala kompletní, i když v ní chyběl zbytek objednávek. Navíc jí chyběla zhruba třetina tabulek — mimo jiné kniha jízd, sanitační deníky, evidence sudů a pohyby sklepa. Teď se stahuje po dávkách a pokud se něco nepovede, záloha to uvede. ⚠️ Doporučení: zapněte si i automatické zálohy přímo v Supabase — appka umí zálohu jen stáhnout, ne obnovit. 🔐 Import Excelu má limit velikosti (omylem vybraný obří soubor dřív zamrzl appku uprostřed inventury) a přibyly bezpečnostní hlavičky. v1.890',
  'ZÁVAŽNÉ — oprava záznamu stáčení vysávala tank: úprava překlepu "35 → 36 sudů" ubrala z tanku 1800 litrů místo padesáti, protože se vrácení původního objemu a odečet nového počítaly ze stejné výchozí hodnoty a druhý přepsal první. Po pár opravách byl tank v aplikaci prázdný, i když byl fyzicky plný. Objem se teď mění relativně přímo v databázi, takže to platí i když stáčejí dva lidé ze stejného tanku naráz. Tlačítko Uložit se navíc odemkne až po dokončení (dvojklik ukládal dvakrát). 🐛 Storno objednávky teď vrátí pivo do skladu — odpočet závozu (běží v 1:00 ráno) dřív zůstal navždy, takže sklad byl trvale nižší o zrušené sudy a v inventuře z toho byl nevysvětlitelný přebytek. v1.888',
  'Zápis bez vybraného piva už neprojde: dřív se stáčení, fasování nebo odpis bez piva uložily a byly vidět v seznamu, ale VŠECHNY skladové výpočty je přeskočily — pivo se tedy nikdy neodečetlo (ani nepřičetlo) a sklad byl trvale špatně, aniž šlo zjistit proč. Teď to hlídá formulář i databáze. 🔐 Smazání piva nebo obalu z číselníku dřív rázem zneviditelnilo všechny jeho historické pohyby (včetně zpětných dopočtů minulých měsíců) — nově to databáze nedovolí a je potřeba pivo označit jako neaktivní. v1.886',
  'Sklad, Dashboard a Inventura si přestaly odporovat: přefuk sudů (přelití piva mezi objemy) počítal jen Sklad — po přefuku 20× 50l na 33× 30l ostatní obrazovky ukazovaly o 20 padesátek víc a o 33 třicítek míň, a v inventuře to vypadalo jako manko u jedné velikosti a přebytek u druhé. Do převodu z minulého měsíce se teď započítává i dorovnání inventury. 📴 Offline stav je konečně vidět i na mobilu — proužek nad spodní lištou ukazuje, že jste offline a kolik zápisů čeká v telefonu (dřív byl ukazatel schovaný a offline zápis vypadal stejně jako uložený). 🔐 Dokončena serverová ochrana práv i u zbylých tabulek; seznam povolených WhatsApp odesílatelů teď smí měnit jen správce. v1.884',
  'Appka je svižnější: při uložení objednávky s 15 položkami se dřív obrazovka přenačítala 15× po sobě (až 225 dotazů z jednoho uložení) — teď se změny sloučí do jednoho načtení. 📱 Export do Excelu šel na mobilu otevřít jen najetím myší, takže na telefonu nefungoval vůbec (Lahve, KEG, Prodejna, Závoz) — teď se rozbalí klepnutím. 🐛 Objednávky konečně ukazují, že se načítají (dřív bylo prázdno a objednávky se pak "samy objevily"). 🔐 Mazání zápisu stáčení lahví se teď ptá (křížek sousedí s plusem, jedno chybné klepnutí mazalo nenávratně) a sanitace kyselinou ve Sklepě varuje, že tank vyprázdní. v1.882',
  'Vrácené prázdné sudy se konečně evidují: okno po zavezení objednávky dosud jen zobrazilo "Zaznamenáno" a nikam nic neuložilo — nešlo zjistit, kdo kolik sudů dluží (a sud stojí 2–3 tisíce). Teď se zápis skutečně ukládá, při chybě se úspěch nehlásí, a v Závozu přibyl přehled "Konto sudů" s tím, kdo má u sebe kolik prázdných KEGů. v1.880',
  'KRITICKÉ — Akce a festivaly se konečně ukládají do databáze: dosud zůstávaly jen v paměti prohlížeče, takže je nikdo jiný neviděl, vymazání dat prohlížeče je smazalo, a hlavně se odvezené pivo NIKDY neodečetlo ze skladu (Sklad, Dashboard i Inventura z toho počítaly, ale tabulka byla prázdná). Odvezete 40 sudů na slavnosti a sklad je dál počítal jako dostupné. Akce zadané dřív se při prvním otevření automaticky převedou. Když se uložení nepovede, appka to teď ohlásí místo tichého selhání. v1.878',
  'Čtení objednávek: pivo napsané jako "sl 11" nebo "sv 12" (barva před číslem) se četlo špatně — číslo se ignorovalo a doplnil se výchozí ležák 12°, takže z jedenáctky byla dvanáctka. Teď číslo u barvy určuje stupeň v obou pořadích ("11sl" i "sl 11") a stupeň napsaný přímo v objednávce má přednost před tím, co odhadne AI. 🔐 Bezpečnost: fotky objednávek z WhatsAppu šlo stáhnout bez přihlášení — kdokoli si mohl nechat vypsat seznam všech souborů; anonymní výpis je zablokovaný. v1.875',
  'Dokončeno vynucení uživatelských práv na serveru: dřív měly ochranu jen Sklep/Stáčení/Inventura — u ostatních modulů (Objednávky, Závoz, Zápis výroby, Kniha jízd, Číselníky, Ceník, Sanitační deníky, Šrotování, Sklo/etikety, Upomínky) appka práva jen schovávala v prohlížeči a technicky zdatný uživatel je mohl obejít. Teď to hlídá i databáze. Pozn.: nic se nezamyká uživatelům, kteří nemají výslovně nastavené omezení. v1.871',
  'Úklid nepoužívaného kódu: odstraněny 2 osiřelé komponenty (starší verze WhatsApp okna a mapy sklepa, dávno nahrazené) a 4 nepoužívané funkce exportu do Excelu — bez dopadu na fungující obrazovky. v1.869',
  'HACCP → Údržba stáčecí linky: celá dlaždice byla jen ukázková data v paměti prohlížeče — po refreshi zmizelo úplně vše, "Odsouhlasit provedení údržby" nikam neukládalo. Teď se plán údržby skutečně ukládá a je sdílený mezi zařízeními. 🐛 Sanitační deník: rozlišení lokálního/uloženého záznamu podle "ID začíná na 17" fungovalo jen náhodou (přestane fungovat cca 2027) — nahrazeno správnou kontrolou formátu. 🐛 Excel export sanitačního deníku: metoda "Kombinovaná sanitace" bez zadané koncentrace se v exportu ukázala jako 0 %, i když na obrazovce správně 2 %. v1.867',
  'Domů: dlaždice "Objednávky k parsování" a tlačítko WhatsApp v horní liště dřív místo okna s WhatsApp zprávami k parsování skončily jen na obyčejném seznamu objednávek — přepnutí stránky a otevření okna se dělalo přes událost, kterou obrazovka Objednávky ještě nestihla začít poslouchat. Teď se to řeší spolehlivě (stejný princip jako u prokliku z "Potřeba stočit"). v1.864',
  'Objednávky: odznak "chybí skladem" u detailu/karty objednávky ignoroval výdej přes fasování, prodejnu a Akce/festivaly — sklad tak vypadal vyšší, než ve skutečnosti byl, a odznak se objevil pozdě nebo vůbec. v1.862',
  'Audit objednávek — sloučení duplicitních položek: dřív šlo o dva samostatné kroky (upravit + smazat), při výpadku uprostřed mohlo množství zůstat tiše zdvojené — teď je to jedna atomická operace. 🔐 WhatsApp: zprávy bez ID webhooku (starší bridge/Tasker) se dřív při opakovaném doručení mohly uložit dvakrát — přidána záložní kontrola podle odesílatele+textu+skupiny v posledních 2 minutách. v1.860',
  'Lahve/KEG — checklist "Začátek stáčení": brána se dřív vázala na editovatelné pole "Datum", takže šlo přepnutím data na jiný den (kde už checklist dřív proběhl) obejít dnešní přípravu pracoviště bez jejího skutečného vyplnění — teď se váže vždy na opravdu dnešní datum. U lahví navíc chyběla druhá kontrola přímo při uložení (spoléhalo se jen na schování formuláře v UI) — teď je tam stejně jako u KEGů. v1.858',
  'Domů: červeno-žluté výstražné dlaždice (Nová aktualizace, Měsíční úklid, STK vozidel) teď jemně pulzují mezi tmavou a světlejší červenou, ať nejdou přehlédnout. 🔐 WhatsApp objednávky: schválení teď zablokuje položku bez rozpoznaného piva/obalu (dřív šlo omylem schválit a položka pak mlčky zmizela ze skladu) — platí pro detail zprávy i pro rychlé schválení jedním klikem ze seznamu. v1.856',
  'Potřeba stočit (Lahve/KEG) a Sklad — počáteční stav: spotřeba piva na Akcích/festivalech (odvezeno − vráceno) se dřív do "co chybí stočit" a do počátečního stavu skladu vůbec nepočítala (jen do obrazovky Sklad/Dashboard) — teď se odečítá všude stejně, napříč Lahve/KEG/Inventura/Plánování stáčení/Dashboard. v1.854',
  'Objednávky: úprava piva/obalu/množství u položky, která už byla fyzicky zavezena (má záznam ve skladovém odpočtu), se dřív nepropsala do skladové evidence — sklad si "pamatoval" jen původní (nesprávnou) hodnotu navždy. Teď se odpočet při úpravě automaticky opraví na aktuální hodnotu. v1.852',
  'Kontrola duplicitních objednávek: chybný filtr v databázovém dotazu (tři OR podmínky bez závorkování) prakticky vždy stáhl skoro celou tabulku objednávek místo jen aktuálního týdne — teď se stahují jen relevantní objednávky. Navíc oprava dne "dnes" bez zadaného data dřív mohla kolem půlnoci spadnout do špatného týdne (UTC vs pražský čas). v1.850',
  'Objednávky: odběratel se u karty i detailu objednávky občas nezobrazil (jen prázdné místo vedle stavu "Nová") — stávalo se, když bylo uložené jméno prázdný řetězec místo chybějící hodnoty; teď se v tom případě dohledá podle odběratele. 🎨 Objednávky: tlačítka dnů v přehledu "Rychlý filtr dne" jsou teď šedá, pokud na daný den není žádná objednávka — amber/zlatá barva zůstává jen u dnů, kde nějaká objednávka je. v1.848',
  'Domů: nová aktualizace appky a nedokončený měsíční úklid se teď ukazují jako tichá dlaždice (červeno-žlutá, jako STK upozornění) místo vyskakovacího okna — sám si klikneš, kdy se ti to hodí. Checklist měsíčního úklidu má nové tlačítko "Udělám na konci týdne" (dřív "OK vím o tom") a dlaždice na Domů zůstává jako připomínka, dokud úklid skutečně neuděláš. 📱 Mobil: horní lišta (Hledat/odznaky/Chyby) na všech obrazovkách kromě Domů zabírala zbytečně místo — teď se na mobilu ukazuje jen název stránky menším písmem, zbytek zůstal na desktopu. v1.846',
  'Objednávky: zápis stáčení/inventury/odpisu se nepropisoval do skladových odznaků v Objednávkách (chybí skladem apod.) bez ručního obnovení stránky — appka poslouchala živé změny jen na objednávkách, ne na stáčení/inventuře/odpisech, které do stejného výpočtu taky vstupují. v1.844',
  'Sklep/KEG: opraveno "% vystočeno" a ztráta při ukončení tanku — po opakovaném použití tanku (nový cyklus) se dřív sčítalo stočené ze VŠECH předchozích cyklů, ne jen z aktuálního. Smazání nebo úprava (množství/pivo/obal/tank) záznamu stáčení teď navíc správně vrátí/odečte objem u sklepního tanku — dřív zůstal navždy posunutý. v1.842',
  'Bezpečnostní audit — kritická oprava: uživatel si mohl přes přímé API volání sám nastavit vlastní modulová práva na plný přístup (server-side kontrola právům slepě věřila) — teď je to na DB úrovni zablokované, stejně jako už dřív u role. Nastavení práv adminem jinému uživateli se navíc dřív tiše neuložilo (appka hlásila úspěch, ale server odmítl zápis) — teď jde přes zabezpečenou serverovou funkci a skutečně se uloží. Auditní log akcí navíc už nejde komukoliv upravit/smazat. v1.840',
  'Upozornění na měsíční úklid: "OK vím o tom" ho teď jen odloží do pátku (kdy se připomene znovu), místo aby zmizelo na celý zbytek měsíce. Nové tlačítko "Už je to provedeno" rovnou označí měsíční checklist (lahve i KEGy) za splněný a zapíše to do obou sanitárních deníků, bez nutnosti procházet checklist ručně. v1.838',
  'Lahve/KEG "Potřeba stočit": sticky hlavička tabulky se špatně přilepila doprostřed a schovávala pod sebou reálné řádky (vypadalo to jako černý pruh, i když data byla v pořádku) — hlavička teď zůstává normálně nahoře. 🖥️ Přidána spodní navigační lišta (Domů a zástupci) i pro notebook/desktop, ne jen mobil — dřív se z appky na desktopu nedalo jinak vrátit na Domů. v1.836',
  'Service worker (offline cache): oprava — appka hledala v cache napříč VŠEMI uloženými verzemi místo jen té aktuální, což po více nasazeních za sebou mohlo výjimečně servírovat smíchané soubory ze staré verze (prázdná/rozbitá stránka po nasazení). Teď se hledá jen v cache aktuálně nainstalované verze. v1.834',
  'Celkový audit vzhledu pro mobil: dlaždice na Domů teď mají tmavý/světlý text podle jasu vlastní barvy (dřív natvrdo bílý — na světlých odstínech skoro nečitelný); zvětšeny malé dotykové prvky (šipky/kolečko u úpravy dlaždice, barevné vzorky, položky v Objednávkách); doladěno posledních pár černých tlačítek (Zahájit stáčení, Detailní přehled, Hotovo, Kontrola zpráv/Audit/Fotka) na amber. v1.832',
  'Objednávky (Nové): tlačítko "Hlasové zadání" mělo jinou výšku než sousední tlačítka (Nové/Text/WhatsApp/Kontrola/Audit/Fotka) — teď je v jedné řadě stejně velké jako ostatní. v1.830',
  'Ikony napříč appkou (Historie, Objednávky, HACCP, Sklad, Inventura, Uživatelé, Sklep): odstraněny zbylé emoji vedle záložek, které už měly lucide ikonu, a doplněny lucide ikony u záložek, které dosud emoji vůbec neměly (Objednávky časový rozsah, Sklep, HACCP kapitoly). v1.828',
  'Lahve (Stáčení) a KEG (Stáčení): záložky "Začátek stáčení / Přehled / Potřeba stočit / Příprava (Checklist) / Konec stáčení / Zadat stáčení" mají teď stejné ikony jako Domů (lucide) místo emoji, a "Příprava"/"Konec" už nejsou černá tlačítka. v1.826',
  'Lahve (Stáčení): checklist "Příprava pracoviště" šlo dřív zavřít jen přes skryté admin tlačítko — křížek (✕), Esc i klik mimo okno teď checklist vždy zavřou i nedokončený (na výslovné přání). v1.824',
  'Lahve (Stáčení → Přehled): záložky "Lahve / KEG / Vše / Měsíc / Týden" mají teď stejné ikony jako zbytek appky (Domů, navigace) místo emoji obrázků. v1.822',
  'Audit barev napříč celou appkou: zhruba 60 černých přepínacích tlačítek (záložky/filtry na 16 obrazovkách — Historie, Objednávky, Kalkulačky, KEG, Lahve, HACCP, Sklad, Inventura, Uživatelé, Sklep, Připomínky, Závoz, Zpětná vazba, Dashboard...) nahrazeno barevnou (amber) verzí; opraven i špatně čitelný bílý text na tlumeném amber pozadí na víc místech a pár míst s téměř neviditelným šedým textem. v1.820',
  'Objednávky (Nové): tlačítka dnů v "Datum závozu" už nejsou černá — barevná (amber), stejná výška jako řádek s týdnem/šipkami. 🎨 Úvodní obrazovka: přibylo 5 nových scén pozadí bližších bílé/modré (Bílá, Modrá, Máta, Levandule, Šedá) vedle původních sytých. v1.818',
  'Úvodní obrazovka: opravena skutečná příčina toho, že "Pozadí" v Upravit rozložení nešlo změnit — kořenový obal appky měl neprůhledné pozadí, které vždy překrylo barevnou scénu (ta se v pozadí correctně nastavovala, jen nebyla nikdy vidět, na žádné stránce, u žádné barvy). v1.816',
  'Úvodní obrazovka: barevné scény pozadí ("Upravit rozložení" → Pozadí) jsou nyní sytější a tmavší — dřív byly téměř bílé pastelové odstíny, na kterých byla změna sotva postřehnutelná ("jako by se pozadí vůbec neměnilo"); vlastní barva pozadí je teď taky výraznější. v1.814',
  'Fasování personál (Přehled): mazání záznamu používalo nativní potvrzovací dialog prohlížeče, který v appce (PWA) uměl zamrznout celou obrazovku bez chybové hlášky — nahrazeno vlastním potvrzovacím oknem appky. v1.812',
  'Fasování personál: záložky "Zápis / Přehled" prohozeny — aktivní záložka je teď tmavě šedá, neaktivní bílá. v1.811',
  'Úvodní obrazovka: tlačítko "Sjednotit barvy dle kategorie" v Upravit rozložení přebarví dlaždice tak, aby všechny ve stejné kategorii (Výroba/Pivovar/Nástroje/Číselníky/Nastavení) měly stejnou barvu. "Přidat dlaždici" teď nabízí i dlaždice umístěné na jiných stránkách (zelená tečka = výběr ji sem přesune) a je seskupené podle kategorie, každá s vlastním odstínem barevné rodiny. v1.809',
  'Úvodní obrazovka: přejetí prstem doleva/doprava přepíná stránky dlaždic (jako Android) — nejen šipky/tečky. Za poslední zaplněnou stránkou vždycky čeká jedna prázdná, ať je kam přetahovat nové dlaždice; jakmile se zaplní, objeví se další prázdná za ní. v1.808',
  'Objednávky: oprava mazání — objednávka s proběhlým automatickým odpočtem závozu se dřív nedala smazat (tichý konflikt v databázi, tvářilo se to, že tlačítko Smazat nic nedělá); teď se smaže i navázaný odpočet a případná chyba se zobrazí. 📉 Odpis: oprava — zápis odpisu vždy selhal na chybějící sloupec, teď funguje. v1.807',
  'Kompletní audit a opravy: přístup jen pro adminem schválené e-maily, povinná změna prvního hesla, bezpečnější oprávnění, offline synchronizace, tisk, AI funkce a transakční zápisy. v1.621',
  'Zabezpečení a spolehlivost: účet lze vytvořit jen pro schválený e-mail, klient už nemůže sám přidělit administrátorskou roli, opraveny duplicitní odpočty závozu a ztráta nových operací při offline synchronizaci. v1.620',
  'Objednávky: nové zadávání objednávek — dlaždice piv (klikni na pivo → obaly a množství), datum závozu (aktuální týden + den), souhrn objednávky dole pod dlaždicemi s úpravou, poznámka s automatickým doplněním data závozu (17.8. / pátek) a zaškrtávací pole 🚰 Půjčení výčepu s rezervačním systémem. v1.619',
  'Odběratelé: tlačítko 🔍 Načíst adresu pro automatické dohledání adresy a telefonu hospody z map/Google, nové pole pro telefon zákazníka a štítky ⚠️ Bez adresy. v1.618',
  'Objednávky: detekce duplicity v týdnu, 1-Click opakování poslední objednávky hospody. 📦 Sklad: červené zvýraznění záporného teoretického deficitu (nestihlo se zapsat stočení). 🚚 Závoz: 1-Click navigace (Mapy/Waze/Mapy.cz), WhatsApp avízo, prázdné sudy a podpis. v1.617',
  'Závoz & Řidič: 1-Click navigace (Google Mapy / Waze / Mapy.cz), WhatsApp odeslání avíza zákazníkovi, dotykový podpis na sklo při převzetí a evidence vrácených prázdných KEG sudů. 🏰 Sklep: Vizuální mapa tanků a CKT s hladinami a zráním. 🍻 Půjčovna výčepů: evidence kaucí, kontaktů a vrácení. 📦 Sklad: rychlé mobilní dotykové sčítadlo. 🎙️ Hlasové diktování ve stáčení lahví. v1.616',
  'Nastavení: přidána možnost změny vlastního jména (používá se v zápisech, např. fasování, stáčení, sanitace). Verze aplikace se přesunula z horní lišty dolů do menu (vedle vašeho jména/stavu připojení) a horní lišta už neotevírá Nastavení — Nastavení zůstává jen v menu. v1.615',

  'KEG (Potřeba stočit): kliknutím na kterýkoliv řádek tabulky potřeb (např. 12° Světlá 50l, chybí 3 ks) se přímo otevře Přehled objednávek s automatickým vyfiltrováním daného piva a sudu v aktuálním týdnu. v1.607',
  'Objednávky (Zadávání): na kartách jednotlivých piv se v odznaku nyní zobrazuje přesný obal i počet kusů (např. 50l 12, 30l 2, 1l 4) místo pouhého celkového součtu kusů. v1.606',
  'Objednávky (Zadávání): pole přejmenováno na „Týden závozu (jiný týden)“ a s tlačítkem „Tento týden“ pro rychlý návrat na aktuální týden. v1.605',
  'Objednávky (Zadávání): Datum závozu / dodání (jiný týden) je nyní primárně předvyplněno aktuálním datem, Den závozu je volitelný výběr a tlačítko „Tento týden“ okamžitě nastaví aktuální týden i datum. v1.604',
  'WhatsApp objednávky (Kontrola a úprava): automatická detekce odběratele z textu/přepisu (Bar, Terasa, Restaurace...), možnost kdykoliv odběratele vybrat/upravit, přímé nastavení data závozu s rychlými volbami (Dnes/Zítra), poznámky k objednávce a plná editace položek (+ / − množství, rychlé počty, výběr piva a obalu, tlačítko smazat × a přidání další položky). v1.603',
  'KEG (Stáčení): checklist „1. Začátek stáčení“ nyní nabízí VOLBU chemie — proplach pivních cest buď NaOH 2% (20 minut), nebo Persteril 0.2% (10 minut) (vybere se vždy jen jeden postup; do Sanitárního deníku KEGů se zapíše zvolená chemie). V posledním týdnu měsíce se nyní zobrazuje varování i pro stáčení KEGů a checklist „4. Měsíční údržba“ je rozšířen: kompletně rozebrat VŠECHNY narážeče a rychlospojky (naložit do louhu NaOH, po 24 h vyčistit kartáčem, opláchnout vodou a zkontrolovat těsnění). v1.593',

  'KEG (Stáčení): checklist „1. Začátek stáčení“ nyní odpovídá aktuálnímu postupu a má 4 kroky — 1) proplach cest: NaOH 2% (20 minut) nebo Persteril 0.2% (10 minut), 2) vystříkat klapky Persterilem 0.2%, 3) oplach klapek vodou, 4) oplach vodou stáčečku (2 minuty); stejné kroky (a jejich pořadí) jsou i v „Části A: Před stáčením“ Sanitárního deníku KEGů, kde vypadl samostatný krok drhnutí klapek louhem. v1.592',
  'Sanitace: u každého kroku sanitárních deníků lahví i KEGů se nyní zaznamenává čas provedení — po odškrtnutí se u kroku objeví pole s časem (předvyplněným aktuálním časem, lze ručně upravit); časy se ukládají a zobrazují v přehledu i exportu do Excelu. Přibyl zcela nový „Sanitární deník výčepů“ (kohouty a výčepní vedení) — kroky s časy, důvodem, provádějící a schvalující osobou, filtrováním podle měsíce a exportem. v1.574',
  'KEG (Stáčení): u každého řádku zápisu se automaticky přiřadí a zobrazí aktivní tank, ze kterého se pivo stáčí (tank se „Zahájeným stáčením“ a daným pivem — např. zadáte 12sv a označí se Tank č.5), a z něj se rovnou odečte stočený objem; pokud je aktivních tanků se stejným pivem víc (2+), řádek výrazně upozorní ⚠️ a nechá vybrat, ze kterého odečítat; nahoře ve formuláři je živý souhrn „Odečte se z tanků“. v1.559',
  'Sanitace: nový „Sanitární deník lahví“ (záložka v Sanitačním deníku) — denní záznam sanitace stáčecí linky lahví: louh NaOH každý den, proplach čistou vodou, celá cesta včetně vzduchové na louhu s opláchem a úklid prostor; po dokončení checklistu „Konec stáčení“ nebo „Měsíční údržba“ se záznam pro dané datum zapíše automaticky; jde editovat, mazat a exportovat do Excelu. v1.558',
  'Lahve (Stáčení): tlačítko „Konec stáčení“ se přesunulo zespodu formuláře zápisu nahoru do hlavičky (vedle „Zadání stočení z fotky“), aby bylo po ruce hned na začátku. v1.557',
  'Lahve (Stáčení): v posledním týdnu měsíce se po přihlášení při každém otevření aplikace zobrazí výrazné upozornění, že je tento týden potřeba udělat měsíční úklid (tlačítko „OK vím o tom“); po splnění úvodního checklistu „1. Začátek stáčení“ se automaticky otevře okno s měsíčním checklistem („4. Měsíční údržba“) s novou položkou — propláchnout veškeré cesty včetně odtokové na pivo, nevyčerpat louh ze sudu všechen (aby tlak vzduchu nevytlačil louh z pivních cest) a nechat do nejbližšího stáčení na stáčečky na louhu; checklist „2. Konec stáčení“ je opět s odškrtávacími políčky. v1.556',
  'Lahve (Stáčení): checklist „2. Konec stáčení“ (úklid) je nyní čistý textový přehled BEZ zaškrtávacích políček — žádné odškrtávání ani „Potvrdit konec stáčení“, jen body k dodržení a tlačítko Zavřít. v1.555',
  'Lahve (Stáčení): ve formuláři zápisu přibylo tlačítko „Konec stáčení“, které otevře checklist „2. Konec stáčení“ (úklid) — položky seřízeny podle aktuálního postupu; „Naplnit“ u úkolu ke stočení teď přepíše celý formulář zápisu vybraným úkolem (pivo + obaly + KEG) a u počtu lahví 1./2./3. obalu se objevily rychlé volby množství v ks. v1.554',
  'Číselníky: sekce „Zadávání stáčení lahví“ (potřeba stáčení na týden + tlačítko „Stočit“) se přesunula z Nastavení (ADMIN) do Číselníků jako nová záložka „Potřeby stáčení“ — je viditelná jen pro administrátory. v1.553',
  'Lahve (Stáčení): položka „Zkontrolovat vnitřky stáčeček a vyčistit kartáčem vnitřní a vnější plochy všech stáčeček (na kterých se bude stáčet) studeným louhem o koncentraci 2% a důkladně opláchnout čistou vodou“ se v checklistu „1. Začátek stáčení“ objeví jen do prvního splnění v týdnu — stačí ji udělat 1× týdně, na dalších stáčeních v tom samém týdnu se už nezobrazuje a neblokuje vstup do zápisu stáčení. v1.552',
  'Nastavení (ADMIN): nová sekce „Zadávání stáčení lahví“ — přehled potřeby na týden (lahve na skladě, sudy na skladě, objednávky + fasování, chybí stočit, konec týdne) a tlačítko „Stočit“, které otevře menu s velikostmi obalů (až 3) a počtem KEG sudů; úkol se uloží a automaticky propíše do formuláře stáčení (Lahve → „Úkoly ke stočení“ → „Naplnit“). v1.551',
  'Lahve (Stáčení): „Stáčecí den“ je nyní povinná brána — po otevření zápisu stáčení se checklist sám otevře a nejde zavřít (Esc, kliknutí mimo ani „Zavřít“), dokud není odškrtnutá celá sekce „1. Začátek stáčení“ (příprava pracoviště); po splnění se uvolní „Pokračovat na stáčení“. Sekce „2. Konec stáčení“, „3. Týdenní kontrola“ a „4. Měsíční údržba“ se dají splnit kdykoli a vstup neblokují. v1.550',
  'Lahve (Stáčení): při vstupu do zápisu stáčení se automaticky otevře „Stáčecí den“ — kontrolní seznam přípravy pracoviště (checklist), dokud není pro daný den splněný; po splnění se už sám neotevírá (tlačítko v liště zůstává). v1.549',
  'Šrotování sladu: kalkulačka v „Kalkulačkách“ přepracovaná na plán šrotování — 4 řádky s rozklikávacím výběrem piva, kolik se šrotuje (kg sladu) a dopočtem pytlů 25 kg; odstraněna vystírka a výpočty °P/výtěžnosti. v1.546',

  'Zabezpečení: z klientské aplikace odstraněn service-role klíč (RLS tak opravdu chrání data — bez přihlášení nikdo nemůže číst WhatsApp zprávy ani ostatní data) a webhook přijímá zprávy jen s hlavičkou x-webhook-token. v1.545',
  'WhatsApp: do aplikace se teď ukládají a importují JEN zprávy ze skupiny „Objednávky pivovar" — webhook zprávy od všech ostatních odesílatelů zahodí (žádný banner, seznam ani počítadlo). Všechny zprávy ze skupiny se rozparsují a zobrazí ke schválení. v1.544',

  'WhatsApp kontrola čtení: nový panel „Kontrola čtení — originál vs. přepis AI“ — originální zpráva se zeleně zvýrazněnými místy, odkud AI četla (s čísly položek), u každé položky ✓/⚠ štítek podle toho, jestli se AI čtený text v originálu opravdu nachází, a rozbalovací „Doslovný přepis AI“; zprávy s nesouhlasícím přepisem mají v Auto-Importu ⚠ odznak. v1.542',

  'Sklad: záložka „Sklo, Etikety, Podtáčky“ (evidence skla, etiket, podtáčků a prázdných lahví) se přesunula z „Odpis, Promo, Sklo, Podtáčky“ do Skladu — v Skladu je nově horní záložka vedle přehledu zásob; tlačítko „Přejít do evidence etiket & lahví“ přepne přímo na tuto záložku. Položka v menu se zkrátila na „Odpis“. v1.541',

  'WhatsApp/poznámky: oprava čtení „ještě sklo“ / „ještě podtácky“ (i s diakritikou) — dříve se taková poznámka nerozpoznala; rozšířeno na všechny tvary „ještě/ještě“ a „podtácky/podtáček“ s/bez diakritiky. v1.540',

  'Objednávky: rozbalovací pole počtu je nově i při zadávání/úpravě objednávek a ve WhatsApp kontrole — podle obalu nabídne keg 4/6/10/12 ks, lahev 0,33/0,5 l 10/20/40/60/80/100 ks a lahev 1/1,5 l 5/6/12/20/24/36/40/50 ks; výchozí položka „+“. v1.538',
  'Prodejna: rychlé pole počtu v Zápisu nově nabízí i 24 a 40 ks (6/10/12/20/24/40); výchozí položka „+“. v1.537',

  'Prodejna: rozbalovací pole počtu (6/10/12/20 ks) je nově i ve formuláři Zápis vedle „−/+“ — jedním klikem nastaví počet a hned uloží; výchozí položka „+“. v1.536',

  'KEG: rychlá pole počtu sudů nově nabízejí i 18 a 36 ks (6/12/18/24/30/36); ve formuláři Zápis je výchozí položka „+". v1.535',

  'KEG: rozbalovací pole počtu sudů je nově i ve formuláři Zápis (vedle „−/+“) — jedním klikem nastaví 6 / 12 / 24 / 30 ks a hned uloží. v1.534',

  'KEG (Přehled i týdenní stáčení): nové rozbalovací pole u počtu sudů — jedním klikem nastaví 6 / 12 / 18 / 24 ks a hned uloží. v1.533',

  'Oprava zoomování dvěma prsty: odstraněn vlastní JS zoom, který bojoval s nativním zoomem prohlížeče a sekal se. Zoom teď plynule obstarává prohlížeč (přiblížení/oddálení prsty, kolečko myši s Ctrl, bez dvojitého zoomu při dvojitém ťuknutí). v1.532',

  'Menu (mobil): odstraněn bílý pruh se zavíracím křížkem nahoře — menu teď začíná až úplně nahoře; zavírá se křížkem v rohu, kliknutím na položku nebo mimo menu. v1.531',

  'Horní tlačítko „WhatsApp" nyní ukazuje červený odznak s počtem zpráv čekajících na schválení — aktualizuje se živě při příchodu i po zpracování zpráv. v1.530',

  'Horní tlačítko „Auto-Import" přejmenováno na „WhatsApp" — jedním kliknutím se otevře přehled objednávek stažených z WhatsAppu (hromadné zpracování a načtení vybraných). v1.529',

  'Úpravy layoutu: odstraněn zajíc (logo) z horní části menu, menu má opět stejnou šířku jako dřív (256 px) a je roztažené svisle až k hornímu okraji. v1.528',

  'Rychlá tlačítka v Nastavení: nově lze vybrat Závoz a všechny stránky/záložky aplikace (výběr z rozbalovacího seznamu, respektuje oprávnění). Odstraněny mrtvé stránky (Varní listy, Stáčení KEG — zadání/přehled) a související mrtvý kód. v1.527',

  'WhatsApp kontrola: po potvrzení/zamítnutí objednávky se zpráva odstraní a automaticky se otevře další čekající zpráva — jde tak kontrolovat jednu po druhé. v1.526',

  'WhatsApp: notifikace o nové objednávce k ověření funguje na VŠECH obrazovkách aplikace (dříve jen na stránce Objednávky) — systémová notifikace, zvuk i banner; kliknutí přepne na Objednávky. v1.525',

  'WhatsApp: oprava — jméno odesílatele zprávy (např. "Miláček") se už nikdy nepoužije jako odběratel. Odběratel (místo, pro které je objednávka) se hledá vždy uvnitř textu zprávy (např. "pro U Dubu"); pokud tam není, objednávka se vytvoří bez odběratele jako "Neznámý odběratel".',

  'WhatsApp: kontrola duplicit při čtení objednávek do aplikace — když dva lidé schválí stejnou objednávku (nebo ji už zadal někdo jiný), systém to pozná (odběratel + týden + položky) a zeptá se před vytvořením. Zabrání to dvojímu zadání téže objednávky.',
  'WhatsApp: lepší čtení — odběratelé, obaly i druhy piva se primárně párují s databází aplikace (přesná shoda, shoda slov, fuzzy, OCR opravy). Čte se i poznámka (výčep, sklo, etikety, vratné lahve, zaplaceno, faktura…) i z řádků s položkami.',
  'WhatsApp: když je ve zprávě konkrétní datum (např. "25.8."), zapíše se do poznámky a objednávka se automaticky přesune do týdne toho data (25.8. = týden 25.8.).',
  'WhatsApp: když je v objednávce výčep (pipa/kohout/výčep…), při schválení se automaticky otevře rezervace výčepu s ověřením dostupnosti v daném termínu.',
  'đź“± WhatsApp: oprava â€” zprĂˇvy, kterĂ© pĹ™iĹˇly, kdyĹľ byla aplikace zavĹ™enĂˇ (nebo na jinĂ© obrazovce), se teÄŹ po otevĹ™enĂ­ ObjednĂˇvek samy doÄŤtou, rozparsujĂ­ a zobrazĂ­ modĂˇl ke schvĂˇlenĂ­. DĹ™Ă­v zĹŻstaly neviditelnĂ©.',
  'đź¤– WhatsApp Auto-Processor: novĂ© tlaÄŤĂ­tko "AI Processing" v objednĂˇvkĂˇch pro automatickĂ© zpracovĂˇnĂ­ WhatsApp zprĂˇv vÄŤetnÄ› OCR obrĂˇzkĹŻ a batch importu.',
  'đź¤– AutomatickĂ˝ import WhatsApp zprĂˇv pĹ™es Make.com: novĂˇ funkce pro automatickĂ˝ pĹ™Ă­jem objednĂˇvek z WhatsApp pomocĂ­ AutoNotification, Tasker a Make.com webhooku.',
  'âšˇ Offline-first PWA: aplikace se vĹľdy otevĹ™e z cache (i bez internetu), navigaÄŤnĂ­ requesty pouĹľĂ­vajĂ­ cache-first strategii pro okamĹľitĂ© naÄŤtenĂ­.',
  'đź“± Reorganizace menu podle tvrzĂ­: verze aplikace pĹ™esunuta do nastavenĂ­, kniha jĂ­zd pĹ™esunuta do Auta, obaly/lahve pĹ™esunuty do Lahve stĂˇÄŤenĂ­, odbÄ›ratelĂ©/piva pĹ™esunuty do InventĂˇĹ™e, upomĂ­nky/poznĂˇmky/kalendĂˇĹ™ slouÄŤeny pod jeden odkaz.',
  'đźŽ¨ CentrĂˇlnĂ­ kontrast napĹ™Ă­ÄŤ celou aplikacĂ­: tmavĂ© panely majĂ­ automaticky svÄ›tlĂ˝ text a svÄ›tlĂ© pozadĂ­ tmavĂ˝ text â€” ĹľĂˇdnĂ© neÄŤitelnĂ© kombinace barev. v1.506',
  'đź› ď¸Ź PĹ™idĂˇnĂ­ listopadu vyÄŤĂ­tĂˇnĂ­ duplicitnĂ­ch objednĂˇvek pĹ™i ÄŤtenĂ­ z fotky: novĂ˝ pokyn pro AI ignorovat opakujĂ­cĂ­ se potvrzenĂ­ (â€žokâ€ś, â€žanoâ€ś, â€žbudemâ€ś, â€žstejnĂ©â€ś) a deduplikaci na Ăşrovni frontendu, aby se stejnĂˇ objednĂˇvka pĹ™i opakovanĂ©m vĂ˝skytu neparsovala vĂ­cekrĂˇt.',


  'đź›˘ď¸Ź â€žPotĹ™eba stoÄŤit KEGyâ€ś: zjednoduĹˇenĂˇ tabulka â€” odstranÄ›ny sloupce inventura/poÄŤ. stav a vĂ˝deje. ZĹŻstĂˇvĂˇ jen Pivo(obal), StoÄŤeno, Sklad, ObjednĂˇno, PotĹ™eba stoÄŤit a Stav (chybĂ­). ÄŚitelnĂ© na mobilu na jednu obrazovku. v1.505',

  'đźŽ¨ OdstranÄ›na ÄŤernĂˇ barva z celĂ© aplikace: pozadĂ­ je svÄ›tle ĹˇedĂ© (mĂ­sto ÄŤernĂ©ho), tmavĂ˝ reĹľim je vypnutĂ˝ â€” ĹľĂˇdnĂ© ÄŤernĂ© plochy ani neÄŤitelnĂ© ÄŤernĂ© pĂ­smo. v1.504',

  'đźŤľ Oprava â€žStĂˇÄŤenĂ­ z fotkyâ€ś (lahve): vybranĂˇ fotka se teÄŹ sprĂˇvnÄ› naÄŤte a zpracuje (dĹ™Ă­ve se uklĂˇdala jen do fronty a nikdy se nespustila). v1.503',

  'đź–Ľď¸Ź ÄŚtenĂ­ z fotky: ikona galerie (đź–Ľď¸Ź) otevĹ™e rovnou fotogalerii (bez dialogu â€žSoubory/Fotogalerieâ€ś). Pro PDF soubory je zvlĂˇĹˇĹĄ tlaÄŤĂ­tko â€žđź“„ PDFâ€ś. v1.502',

  'đź“¸ ÄŚtenĂ­ z fotky: upozornÄ›nĂ­ na duplikĂˇt funguje i pro fotky, kterĂ© jsi naÄŤetl dĹ™Ă­ve (pamatuje se otisk naÄŤtenĂ˝ch fotek). HromadnĂ© naÄŤĂ­tĂˇnĂ­ (napĹ™. 50 fotek) se uklĂˇdĂˇ do fronty a ÄŤte jedna po druhĂ©. v1.501',

  'đź–Ľď¸Ź ÄŚtenĂ­ objednĂˇvek z fotky: vedle tlaÄŤĂ­tka fotoaparĂˇtu (đź“·) je teÄŹ ikona galerie (đź–Ľď¸Ź) â€” kliknutĂ­m se otevĹ™e galerie / vĂ˝bÄ›r souboru. v1.500',

  'đźŽ¨ Detail objednĂˇvky: pozadĂ­ je teÄŹ ĹˇedĂ© (mĂ­sto ÄŤernĂ©ho/tmavĂ©ho v tmavĂ©m reĹľimu) â€” lepĹˇĂ­ ÄŤitelnost i pĹ™i otevĹ™enĂ©m detailu. v1.499',

  'đź—“ď¸Ź PĹ™ehled objednĂˇvek: v reĹľimu â€žCelĂ˝ mÄ›sĂ­câ€ś pĹ™idĂˇny Ĺˇipky â€ą â€ş pro pĹ™epĂ­nĂˇnĂ­ mÄ›sĂ­cĹŻ (tĂ˝dny Ĺˇipky uĹľ mÄ›ly) â€” stejnÄ› jako u stĂˇÄŤenĂ­ KEG/lahvĂ­. v1.498',

  'đźŤş Oprava automatickĂ© rezervace vĂ˝ÄŤepu: rezervace se uĹľ nevytvoĹ™Ă­, kdyĹľ poznĂˇmka objednĂˇvky obsahuje jen bÄ›ĹľnĂˇ slova (â€žbarâ€ś, â€žhospodaâ€ś, â€žpivniceâ€ś, â€žstojanâ€ś) â€” spustĂ­ se jen pĹ™i reĂˇlnĂ© zmĂ­nce o vĂ˝ÄŤepu (vĂ˝ÄŤep/pipa/kohout...). v1.497',

  'đźŽ¨ ÄŚitelnost objednĂˇvek: odstranÄ›ny skoro-ÄŤernĂ© texty (â€‘950/â€‘900) v seznamu a v rozkliknutĂ©m detailu objednĂˇvky nahrazeny tmavÄ› Ĺˇedou/ÄŤitelnÄ›jĹˇĂ­ barvou â€” bez ÄŤernĂ©, lepĹˇĂ­ ÄŤitelnost. v1.496',

  'đźŤş U objednĂˇvky s rezervacĂ­ vĂ˝ÄŤepu se zobrazĂ­ ikona đźŤş a nĂˇzev vĂ˝ÄŤepu. ObjednĂˇvka na budoucĂ­ termĂ­n (napĹ™. 25.8.) se Ĺ™adĂ­ do tĂ˝dne toho termĂ­nu a na zaÄŤĂˇtku toho tĂ˝dne + den pĹ™edem se spustĂ­ upozornÄ›nĂ­. v1.495',

  'đź“ť Oprava poznĂˇmky u objednĂˇvky z fotky: pĹ™estanou se tam zapisovat vĂˇgnĂ­ slova jako â€žbarâ€ś nebo samostatnĂ© â€žsklo?â€ś (zĹŻstane jen reĂˇlnĂ˝ poĹľadavek, napĹ™. â€žpĹ™idat skloâ€ś, â€žvĂ˝ÄŤepâ€ś). v1.494',

  'âž• PĹ™idat Ĺ™Ăˇdek pĹ™i ÄŤtenĂ­ z fotky (objednĂˇvky) se teÄŹ vloĹľĂ­ hned na mĂ­sto, kde prĂˇvÄ› pĂ­ĹˇeĹˇ (za aktuĂˇlnĂ­ Ĺ™Ăˇdek), ne vĹľdy dolĹŻ na konec. v1.493',

  'đźŤş Oprava ÄŤtenĂ­ â€ž2x50â€ś z fotky: pokud AI pĹ™eÄŤte jen â€ž2x50â€ś (2Ă— sud 50l) a nedoplnĂ­ obal/mnoĹľstvĂ­, aplikace to teÄŹ odvodĂ­ sama pĹ™Ă­mo z textu â€” objednĂˇvka se uĹľ neztratĂ­. v1.492',

  'âš ď¸Ź VrĂˇceno tlaÄŤĂ­tko â€žChybyâ€ś nahoĹ™e v zĂˇhlavĂ­ (ÄŤervenĂ©) â€” mrkveckĂ˝m, uvÄ›domĂ­Ĺˇ chybu nebo nĂˇpad rovnou s moĹľnostĂ­ pĹ™iloĹľit fotku. v1.491',

  'đźŤş StupeĹ piva teÄŹ patĹ™Ă­ k tĂ© objednĂˇvce, u kterĂ© je na fotce napsanĂ˝: AI uĹľ nemĹŻĹľe zamÄ›nit stupeĹ z jinĂ© objednĂˇvky (napĹ™. â€ž2x50â€ś dostane sprĂˇvnĂ˝ stupeĹ z vlastnĂ­ fotky, ne z jinĂ©ho Ĺ™Ăˇdku). Opraveno i pro samostatnÄ› rozpoznanĂ˝ stupeĹ. v1.490',

  'đź“˛ ÄŚtenĂ­ z fotky (objednĂˇvky): kdyĹľ se stejnĂˇ objednĂˇvka pĹ™eÄŤte z fotky vĂ­ckrĂˇt (duplicitnĂ­ Ĺ™Ăˇdky od AI), aplikace ji teÄŹ vrĂˇtĂ­ jen jednou â€” automatickĂˇ deduplikace podle odbÄ›ratele, piva, obalu, stupnÄ›, mnoĹľstvĂ­ a data. v1.489',
  'đź“¸ ÄŚtenĂ­ z fotky (objednĂˇvky): nahrĂˇĹˇ-li 2Ă— tentĂ˝Ĺľ snĂ­mek obrazovky, aplikace tÄ› na to upozornĂ­ a umoĹľnĂ­ ho pĹ™eskoÄŤit (detekce podle nĂˇzvu, velikosti a ÄŤasu souboru). v1.489',
  'đź’¬ WhatsApp (AI): ÄŤtenĂ­ objednĂˇvek bere v Ăşvahu KONTEXT celĂ© konverzace. KdyĹľ se na objednĂˇvku odpovĂ­dĂˇ (â€žjeĹˇtÄ› k tomuâ€ś, â€žpĹ™idejâ€ś apod.), odpovÄ›ÄŹ se doplnĂ­ do pĹŻvodnĂ­ objednĂˇvky stejnĂ©ho odbÄ›ratele/data a neÄŤte se tupe Ĺ™Ăˇdek po Ĺ™Ăˇdku. TotĂ©Ĺľ platĂ­ pro screenshoty konverzace (fotka). v1.489',

  'âšˇ Oprava pĂˇrovĂˇnĂ­ piva Jantar (13Â° Jantar polotmavĂ˝ leĹľĂˇk): zabrĂˇnÄ›no pĹ™esmÄ›rovĂˇnĂ­ na 12Â° SvÄ›tlĂˇ z obecnĂ˝ch aliasĹŻ. v1.488',
  'âšˇ Oprava pĂˇrovĂˇnĂ­ lahvĂ­ 20x0,5: Ĺ™etÄ›zce "20x0,5" se bezpeÄŤnÄ› pĹ™iĹ™azujĂ­ k obalu Lahve 0.5l (nikoliv 0,33l). v1.487',
  'âšˇ Oprava pĂˇrovĂˇnĂ­ 50l sudĹŻ: explicitnĂ­ vyhodnocenĂ­ objemu 50l pĹ™ed aliasem "keg" (kterĂˇ zpĹŻsobovala pĹ™epis na 30l). v1.486',
  'âšˇ SW Network-First oprava: Vynuceno naÄŤĂ­tĂˇnĂ­ nejnovÄ›jĹˇĂ­ho kĂłdu ze sĂ­tÄ› bez zasekĂˇvĂˇnĂ­ na starĂ© cache. v1.485',
  'đź“‹ KompletnĂ­ oficiĂˇlnĂ­ KontrolnĂ­ seznam (56 bodĹŻ: ZaÄŤĂˇtek, Konec, TĂ˝dennĂ­ a MÄ›sĂ­ÄŤnĂ­ ĂşdrĹľba stĂˇÄŤenĂ­ lahvĂ­).',
  'đź“Ą PĹ™idĂˇno tlaÄŤĂ­tko a modul "Import z Excelu / Google Tabulky" do Inventury s automatickĂ˝m pĂˇrovĂˇnĂ­m piva a obalu.',
  'âšˇ Opravena barva pĂ­sma v BilanÄŤnĂ­ tabulce inventury na vĂ˝raznÄ› tmavĂ© + vylepĹˇeno 2-prstovĂ© gest pinch-to-zoom pro celou aplikaci.',
  'đź“‹ PridĂˇn KontrolnĂ­ seznam (Checklist) pro StĂˇÄŤenĂ­ lahvĂ­ (sanitace, obaly, etikety, ĹˇarĹľe, DMT, kontrola plnÄ›nĂ­ a Ăşklid).',
  'âšˇ AutomatickĂˇ aktualizace verze: Opraven kontrast textĹŻ v objednĂˇvkĂˇch a inventuĹ™e, zapracovĂˇno neomylnĂ© zĂˇchrannĂ© pĂˇrovĂˇnĂ­ piva a obalu, aktivovĂˇn 2-prstovĂ˝ pinch-zoom pro celou aplikaci.',
  'âšˇď¸Ź Oprava fronty fotografiĂ­: KompletnÄ› pĹ™epsĂˇn mechanismus zpracovĂˇnĂ­ fronty fotografiĂ­ na pozadĂ­ pomocĂ­ sekvenÄŤnĂ­ho asynchronnĂ­ho cyklu (async/await). OdstranÄ›na zĂˇvislost na sloĹľitĂ©m a chybovĂ©m provĂˇzĂˇnĂ­ React efektĹŻ, coĹľ zaruÄŤuje 100% spolehlivost pĹ™i nahrĂˇvĂˇnĂ­ libovolnĂ©ho mnoĹľstvĂ­ snĂ­mkĹŻ, a to i v kombinaci s editorem oĹ™ezĹŻ pĹ™ed odeslĂˇnĂ­m na AI.',
  'đź“¸ AutomatickĂˇ fronta fotografiĂ­: PĹ™i vĂ˝bÄ›ru nebo vyfocenĂ­ vĂ­ce snĂ­mkĹŻ najednou se nynĂ­ vĹˇechny fotky zpracujĂ­ na pozadĂ­ automaticky jedna po druhĂ© (do spoleÄŤnĂ© fronty). VĂ˝sledky se postupnÄ› pĹ™ipojujĂ­ a uĹľivatel je mĹŻĹľe zkontrolovat a importovat najednou, namĂ­sto dĹ™Ă­vÄ›jĹˇĂ­ho zdlouhavĂ©ho ÄŤekĂˇnĂ­ a schvalovĂˇnĂ­ po jednotlivĂ˝ch snĂ­mcĂ­ch.',
  'đź“± DynamickĂˇ hlaviÄŤka importu: OdstranÄ›n statickĂ˝ text â€žRozparsovanĂ© poloĹľkyâ€ś v hlaviÄŤce a nahrazen textem, kterĂ˝ AI pĹ™eÄŤetla na aktuĂˇlnÄ› vybranĂ©m/upravovanĂ©m Ĺ™Ăˇdku. ZobrazenĂ­ se automaticky a okamĹľitÄ› mÄ›nĂ­ pĹ™i pĹ™echodu nebo kliknutĂ­ na jakĂ˝koli vstup jinĂ©ho Ĺ™Ăˇdku, takĹľe pĹ™i psanĂ­ pod sebou na mobilu mĂˇte stĂˇle na oÄŤĂ­ch originĂˇlnĂ­ text z fotky.',
  'đź“± Vzhled na mobilu: VĂ˝raznÄ› zvÄ›tĹˇena a zpĹ™ehlednÄ›na textovĂˇ pole a rozbalovacĂ­ vĂ˝bÄ›ry (pivo, obal) pĹ™i importech z fotek/AI (objednĂˇvky, stĂˇÄŤenĂ­, inventura). Na mobilu se nynĂ­ pole roztahujĂ­ na plnou ĹˇĂ­Ĺ™ku a majĂ­ vÄ›tĹˇĂ­ pĂ­smo, coĹľ usnadĹuje kontrolu a zabraĹuje nechtÄ›nĂ©mu pĹ™iblĂ­ĹľenĂ­ v prohlĂ­ĹľeÄŤi.',
  'âš ď¸Ź NahlaĹˇovĂˇnĂ­ chyb: PĹ™idĂˇno rychlĂ© ÄŤervenĂ© tlaÄŤĂ­tko â€žChybyâ€ś nahoĹ™e v zĂˇhlavĂ­ pro snadnĂ© hlĂˇĹˇenĂ­ zĂˇvad a nĂˇpadĹŻ na vylepĹˇenĂ­ pĹ™Ă­mo s moĹľnostĂ­ pĹ™iloĹľit fotku z galerie ÄŤi fotoaparĂˇtu. Fotky se automaticky zmenĹˇujĂ­ a komprimujĂ­ na pozadĂ­ a sprĂˇvce je uvidĂ­ pĹ™ehlednÄ› v poznĂˇmkĂˇch a nĂˇpadech.',
  'âśŹď¸Ź Ăšprava stĂˇÄŤenĂ­: U stĂˇÄŤenĂ­ lahvĂ­ i KEG sudĹŻ byla pĹ™idĂˇna moĹľnost kompletnĂ­ a detailnĂ­ editace zĂˇznamĹŻ (kliknutĂ­m na ikonu tuĹľky âśŹď¸Ź) â€” lze upravit datum, pivo, obal, mnoĹľstvĂ­, tank i poznĂˇmku.',
  'đźŤľ StĂˇÄŤenĂ­ lahvĂ­ (PĹ™ehled): poÄŤet sudĹŻ â€žđź›˘ď¸Ź SudĹŻâ€ś i velikost â€žKEGâ€ś jsou nynĂ­ EDITOVATELNĂ‰ pĹ™Ă­mo v pĹ™ehledu â€” poÄŤet sudĹŻ tlaÄŤĂ­tky â’ / + a velikost sudu rozbalovacĂ­m vĂ˝bÄ›rem; zmÄ›na se projevĂ­ pro celou ĹˇarĹľi (vĹˇechny obaly stoÄŤenĂ© z danĂ˝ch sudĹŻ) a pĹ™epoÄŤĂ­tĂˇ se i zdrojovĂ˝ objem a ztrĂˇta',
  'đźŤľ StĂˇÄŤenĂ­ lahvĂ­ (PĹ™ehled): KEG a poÄŤet sudĹŻ lze nynĂ­ DOPLNIT i u zĂˇznamĹŻ, kde byl KEG zapomenut â€” u kaĹľdĂ© ĹˇarĹľe bez zadanĂ©ho sudu je aktivnĂ­ vĂ˝bÄ›r velikosti KEG a tlaÄŤĂ­tka â’ / + pro poÄŤet sudĹŻ (dĹ™Ă­ve se zobrazovala jen pomlÄŤka)',


  'đź“· Import z fotky (AI): oprava pĹ™iĹ™azenĂ­ OBJEMU u KEG sudĹŻ â€” pokud je v textu objednĂˇvky napsĂˇno â€ž2x50â€ś (pĹ™esnÄ› viditelnĂ© v textu), ale AI do obalu zapĂ­Ĺˇe â€ž2x30â€ś nebo â€žKEG 30lâ€ś, aplikace nynĂ­ sprĂˇvnÄ› pouĹľije objem z textu (50l) a nenechĂˇ chybnĂ˝ obal 30l. TĂ˝kĂˇ se i fragmentĹŻ typu â€ž2x30â€ś, kterĂ© AI omylem zapĂ­Ĺˇe jako obal.',

  'đźŤş Jantar: pivo â€žJantarâ€ś mĂˇ nynĂ­ jednoznaÄŤnou pĹ™ednost â€” pokud v objednĂˇvce zaznĂ­/napĂ­Ĺˇe â€ž12 jantarâ€ś, â€žjantâ€ś nebo â€žjantarekâ€ś, vĹľdy se vybere pivo Jantar (ne 12Â° SvÄ›tlĂˇ), i kdyby u nÄ›j stĂˇlo ÄŤĂ­slo 12. Opraveno pro ruÄŤnĂ­ zadĂˇnĂ­ textem, hlas i fotku.',
  'đźŤľ StĂˇÄŤenĂ­ lahvĂ­ (PĹ™ehled): pĹ™idĂˇn sloupec â€žđź›˘ď¸Ź SudĹŻâ€ś â€” ukazuje, z kolika sudĹŻ byly lahve stoÄŤeny (z pole kegs_used); v souhrnu â€žCelkemâ€ś je celkovĂ˝ poÄŤet pouĹľitĂ˝ch sudĹŻ (s deduplikacĂ­ zdroje)',
  'đźŤľ StĂˇÄŤenĂ­ lahvĂ­ (PĹ™ehled): pĹ™idĂˇny zĂˇloĹľky đźŤľ Lahve / đź›˘ď¸Ź KEG / đź“¦ VĹˇe pro oddÄ›lenĂ­ zĂˇznamĹŻ lahvĂ­ a KEG sudĹŻ',
  'đźŤľ StĂˇÄŤenĂ­ lahvĂ­ (PĹ™ehled): u zobrazenĂ­ â€žMÄ›sĂ­câ€ś pĹ™idĂˇna navigace â€ą / â€ş pro listovĂˇnĂ­ mezi mÄ›sĂ­ci (dĹ™Ă­ve Ĺˇlo listovat jen u tĂ˝dnĹŻ)',
  'đź“‹ Inventura: sloupec â€žVĂ˝d.â€ś (vĂ˝deje) ve FyzickĂ© inventuĹ™e nynĂ­ zahrnuje VĹ ECHNY odchody ze skladu â€” FasovĂˇnĂ­ + Prodejna + Odpis + ObjednĂˇvky + StĂˇÄŤenĂ­ lahvĂ­ + Akce (dĹ™Ă­ve jen FasovĂˇnĂ­ + Prodejna + Odpis)',

  'đź›˘ď¸Ź KEG (StĂˇÄŤenĂ­ & PĹ™ehled): â€žZbĂ˝vĂˇ stoÄŤit kegâ€ś se nynĂ­ poÄŤĂ­tĂˇ jako objednĂˇno â’ (sklad na konci mÄ›sĂ­ce + stoÄŤeno tento mÄ›sĂ­c) â€” porovnĂˇvĂˇ se s inventurou a stĂˇÄŤenĂ­m v aktuĂˇlnĂ­m mÄ›sĂ­ci',
  'đź“‹ Inventura: pĹ™idĂˇn mÄ›sĂ­ÄŤnĂ­ filtr (â€ą / â€ş) pĹ™Ă­mo do zĂˇloĹľky â€žStav sudĹŻ na konci mÄ›sĂ­ceâ€ś (BilanÄŤnĂ­ konto sudĹŻ) â€” lze si vyfiltrovat libovolnĂ˝ mÄ›sĂ­c (napĹ™. ÄŤervenec) a celĂ© konto se pĹ™epoÄŤĂ­tĂˇ',


  'ďż˝ Sklad: na kartÄ› piva pĹ™idĂˇn Ĺ™Ăˇdek â€žCelkem odchodyâ€ś (fasovĂˇnĂ­ + stĂˇÄŤenĂ­ lahvĂ­ + akce + objednĂˇvky + odpisy + prodejna) a reĂˇlnĂ˝ stav â€žK dispozici (po vĹˇech odchodech)â€ś',
  'đź›˘ď¸Ź Inventura: opraveno â€žStĂˇÄŤenĂ­ lahvĂ­â€ś v bilanÄŤnĂ­m kontu sudĹŻ â€” nynĂ­ se sprĂˇvnÄ› odeÄŤĂ­tajĂ­ pouĹľitĂ© sudy ze skladu sudĹŻ (napĹ™. 2Ă—50L na 94 ks 1L PET); lahve stoÄŤenĂ© bez sudĹŻ (dotĂˇÄŤenĂ­ z akcĂ­) se pĹ™iÄŤtou do skladu lahvĂ­, ale sudy se neodeÄŤĂ­tajĂ­',

  'ďż˝đź”„ AutomatickĂˇ aktualizace: aplikace se nynĂ­ sama aktualizuje po kaĹľdĂ©m nasazenĂ­ novĂ© verze (kontrola kaĹľdou minutu) â€” bez nutnosti ruÄŤnÄ› obnovovat strĂˇnku; pokud zrovna pĂ­Ĺˇete do formulĂˇĹ™e, aktualizace poÄŤkĂˇ, aĹľ dokonÄŤĂ­te zĂˇpis',
  'đź“¦ Sklad: â€žSklademâ€ś nynĂ­ = stav k zaÄŤĂˇtku mÄ›sĂ­ce (inventura) + stoÄŤeno â’ VĹ ECHNY odchody (fasovĂˇnĂ­/scenĂ˝ sud, odpisy, stĂˇÄŤenĂ­ lahvĂ­, akce, objednĂˇvky). Po zadĂˇnĂ­ scenĂ©ho sudu se poÄŤet sudĹŻ v pĹ™ehledu sprĂˇvnÄ› snĂ­ĹľĂ­',
  'đź“¦ Sklad: detail po obalech nynĂ­ ukazuje VĹ ECHNY odchody v samostatnĂ˝ch sloupcĂ­ch â€” ObjednĂˇvky, Odpisy, FasovĂˇnĂ­, Akce, StĂˇÄŤenĂ­ lahvĂ­ a Celkem odchody; objednĂˇvky se odeÄŤĂ­tajĂ­ v tĂ˝dnu zĂˇvozu (delivery_date)',



  'đźŤľ StĂˇÄŤenĂ­ lahvĂ­: pĹ™idĂˇn druhĂ˝ sloupec â€žLahve 2â€ś â€” z jednoho sudu lze stoÄŤit vĂ­ce druhĹŻ obalĹŻ najednou (napĹ™. 0,5L i 1,5L); opravena nabĂ­dka lahvĂ­, kde chybÄ›ly 1,5L lahve',

  'đźŤľ StĂˇÄŤenĂ­ lahvĂ­: pĹ™i stĂˇÄŤenĂ­ do lahvĂ­ ze sudĹŻ se zadĂˇvĂˇ poÄŤet pouĹľitĂ˝ch sudĹŻ (napĹ™. 6Ă—50L) vedle obalu; tyto sudy se odeÄŤtou ze skladu KEG (jako objednĂˇvka) a v pĹ™ehledu vytraty je vidÄ›t zdroj ze sudĹŻ, stoÄŤeno do lahvĂ­ a ztrĂˇta (litry i %)',

  'đź›˘ď¸Ź StĂˇÄŤenĂ­ KEG: pĹ™ehled je nynĂ­ na samostatnĂ© zĂˇloĹľce â€žPĹ™ehledâ€ś (oddÄ›leno od zĂˇpisu); nahoĹ™e je vidÄ›t â€žZbĂ˝vĂˇ stoÄŤit kegâ€ś a pod nĂ­m pĹ™ehled stoÄŤenĂ˝ch sudĹŻ s filtrem podle dne/tĂ˝dne/mÄ›sĂ­ce a podle piva',


  'đźŹšď¸Ź Sklep & Spilka: na kartÄ› tanku je nynĂ­ pĹ™Ă­mĂˇ volba piva a poÄŤĂˇteÄŤnĂ­ho objemu (bez otevĂ­rĂˇnĂ­ â€žUpravitâ€ś); u kaĹľdĂ©ho tanku je vidÄ›t poÄŤĂˇteÄŤnĂ­ objem a kolik piva zbĂ˝vĂˇ v HL',
  'đźŹšď¸Ź Sklep & Spilka: odstranÄ›n HACCP banner nahoĹ™e; statistiky (souhrn mÄ›sĂ­c/rok, historie cyklĹŻ a pĹ™etĂˇÄŤenĂ­) pĹ™esunuty do Statistiky â€” ve Sklepu zĹŻstĂˇvĂˇ jen pĹ™ehled tankĹŻ a spilky',
  'đź“‹ ObjednĂˇvky: karty objednĂˇvek majĂ­ nynĂ­ jednotnou bĂ­lou barvu (bez podbarvenĂ­ dnem/pivem); jednotlivĂˇ piva jsou barevnÄ› rozliĹˇenĂˇ teÄŤkou u nĂˇzvu ve stejnĂ©m stylu jako StĂˇÄŤenĂ­ (keg/lahve)',
  'đź“‹ ObjednĂˇvky: zĂˇloĹľka â€žObjednĂˇvkyâ€ś pĹ™ejmenovĂˇna na â€žPĹ™ehledâ€ś; v pĹ™ehledu a zĂˇvozu sjednoceny ikony do jednotnĂ©ho stylu (lucide) a zpĹ™ehlednÄ›ny barvy â€” tmavÄ› ĹľlutĂ© texty nahrazeny ÄŤitelnÄ›jĹˇĂ­mi (ÄŤernĂˇ na ĹľlutĂ©m podkladu, bĂ­lĂˇ na jantarovĂ©m)',
  'đź“‹ ObjednĂˇvky: ZĂˇvoz je nynĂ­ tĹ™etĂ­ zĂˇloĹľkou vedle NovĂ© a ObjednĂˇvky â€” nahoĹ™e jsou vĹľdy zĂˇloĹľky NovĂ© / ObjednĂˇvky / ZĂˇvoz, aĹĄ kliknete na kteroukoli; obsah zĂˇvozu se zobrazĂ­ pĹ™Ă­mo v objednĂˇvkĂˇch',
  'đźŽ¨ ObjednĂˇvky a ZĂˇvoz: sjednoceny ikony do jednotnĂ©ho stylu (lucide) â€” NovĂ© (+), ObjednĂˇvky (faktura), ZĂˇvoz (dodĂˇvka), WhatsApp, Fotka/AI, Tisk, Export, FasovĂˇnĂ­, Smazat, Vybrat vĹˇe a dalĹˇĂ­',
  'đź“‹ ObjednĂˇvky: â€žDetaily obj.â€ś pĹ™ejmenovĂˇno na â€žObjednĂˇvkyâ€ś; v kartÄ› objednĂˇvky je hlavnĂ­ datum akce/zĂˇvozu (napĹ™. 21.8) a datum zadĂˇnĂ­ je vedlejĹˇĂ­; opravena kontrola â€žVĹˇe sklademâ€ś â€” poÄŤĂ­tĂˇ se podle tĂ˝dne zĂˇvozu, ne zadĂˇnĂ­; â€žPĹ™ipr.â€ś je vedle â€žVĹˇe sklademâ€ś; zĂˇloĹľka â€žNovĂ©â€ś zobrazuje jen formulĂˇĹ™ zadĂˇvĂˇnĂ­, seznam a detaily jen v â€žObjednĂˇvkyâ€ś',
  'đź“‹ ObjednĂˇvky: tlaÄŤĂ­tka ZadĂˇnĂ­ objednĂˇvek, Detaily objednĂˇvek a ZĂˇvoz na jednom Ĺ™Ăˇdku; opraven filtr poloĹľek â€” vĂ˝bÄ›r piva a velikosti obalu se kombinuje (napĹ™. 11SV + 30L zobrazĂ­ jen objednĂˇvky s obojĂ­m)',
  'đź“‹ ObjednĂˇvky: zĂˇloĹľka â€žPĹ™ehledâ€ś pĹ™ejmenovĂˇna na â€žZadĂˇnĂ­ objednĂˇvekâ€ś; v â€žDetaily objednĂˇvekâ€ś odstranÄ›n formulĂˇĹ™ zadĂˇvĂˇnĂ­, pole â€žDenâ€ś pĹ™ejmenovĂˇno na â€žZĂˇvozâ€ś, odstranÄ›no FasovĂˇnĂ­, opravena viditelnost tlaÄŤĂ­tek ZruĹˇit/Smazat na telefonu a pĹ™idĂˇny filtry podle piva a velikosti obalu',
  'đź“‹ ObjednĂˇvky: PĹ™ehled nynĂ­ zobrazuje VĹ ECHNY zadanĂ© objednĂˇvky â€” lze nastavit den zĂˇvozu, upravit objednĂˇvku a vidÄ›t vĹˇechny objednanĂ© poloĹľky',
  'đźšš ZĂˇvoz: filtr dnĹŻ â€” â€žVĹˇechny dnyâ€ś pĹ™ejmenovĂˇno na â€žVĹˇechnyâ€ś, odstranÄ›na ÄŤĂ­sla, zvĂ˝raznÄ›ny jen dny se zĂˇvozem',
  'đźšš Historie a pĹ™ehled tras pĹ™esunuty ze ZĂˇvozu do Statistiky (zĂˇloĹľka â€žHistorie a pĹ™ehled trasâ€ś)',
  'đźšš ZĂˇvoz: datum zmenĹˇen, tlaÄŤĂ­tka ZadĂˇvĂˇnĂ­ objednĂˇvek a PĹ™ehled objednĂˇvek pĹ™esunuta nahoru, odstranÄ›no Diktovat hlasem, CelkovĂˇ vĂˇha a Zavezeno na jednom Ĺ™Ăˇdku a zmenĹˇeny',
  'đźšš ZĂˇvoz: historie a pĹ™ehled tras â€” pĹ™idĂˇny filtry (dny/tĂ˝dny/mÄ›sĂ­ce, odbÄ›rnĂ© mĂ­sto, pivo, velikost obalu)',
  'đź“‹ ObjednĂˇvky: grafickĂˇ optimalizace karet objednĂˇvek na kompaktnĂ­ Ĺ™Ăˇdky, aby se v telefonu veĹˇlo vĂ­ce poloĹľek',
  'đź“‹ ObjednĂˇvky: tlaÄŤĂ­tka PĹ™ehled, Detaily objednĂˇvek a ZĂˇvoz pĹ™esunuty nahoru nad hlasovĂ© zadĂˇvĂˇnĂ­, WhatsApp a fotku',
  'đź“‹ ObjednĂˇvky: odstranÄ›n souhrn tĂ˝dne (pĹ™ehled objednĂˇvek a kusĹŻ jednotlivĂ˝ch sudĹŻ)',
  'đźšš ObjednĂˇvky: tlaÄŤĂ­tko ZĂˇvoz nahoĹ™e otevĂ­rĂˇ strĂˇnku ZĂˇvoz',
  'đźš° Rezervace vĂ˝ÄŤepu: rozpoznĂˇvĂˇnĂ­ vĹˇech synonym (jednokohout, dvojkohout, dvojpĂ­pa, trojpĂ­pa, pĂ­pa, vĂ˝ÄŤepâ€¦) a vĂ˝bÄ›r druhu vĂ˝ÄŤepu',
  'đźš° Rezervace vĂ˝ÄŤepu se propisuje do zĂˇloĹľky VĂ˝ÄŤepy',
  'đź“ť ZadĂˇvĂˇnĂ­ objednĂˇvek: odstranÄ›n sloupec OdbÄ›ratel z tabulky, roztaĹľen sloupec Pivo (odbÄ›ratel je nahoĹ™e v hlaviÄŤce)',
];
