plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "D:\\stazene\\zajic\\project\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "pnpm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sw.js"
to = "/sw.js"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/manifest.webmanifest"
to = "/manifest.webmanifest"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/icon-192.png"
to = "/icon-192.png"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/icon-512.png"
to = "/icon-512.png"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/icon-maskable-512.png"
to = "/icon-maskable-512.png"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]